// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  addPartnerUsersMePartnersPartnerIdPost,
  createPeriodEventPeriodPost,
  createSymptomEventSymptomsPost,
  createTempReadingTempPost,
  createUserUsersPost,
  deleteMeUsersMeDelete,
  deletePeriodPeriodMePeriodIdDelete,
  deleteSymptomEventSymptomsMeSymptomIdDelete,
  deleteTempTempMeTemperatureIdDelete,
  exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGet,
  exportSymptomsCsvSymptomsMeCsvGet,
  getAllPeriodsPeriodGet,
  getMyEventsCsvUsersMeEventsCsvGet,
  getMyEventsUsersMeEventsGet,
  getMyPartnersUsersMePartnersGet,
  getMyPeriodsCsvPeriodMeCsvGet,
  getMyPeriodsPeriodMeGet,
  getMyReadingsTempMeGet,
  getMySymptomEventsSymptomsMeGet,
  getMyTempAveragesTempMeAveragesGet,
  getMyTempReadingsCsvTempMeCsvGet,
  getNextPeriodPeriodMeNextGet,
  getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGet,
  getPartnerPeriodsPeriodPartnerPartnerIdGet,
  getPartnerSymptomsSymptomsPartnerPartnerIdGet,
  getPartnerTemperaturesTempPartnerPartnerIdGet,
  getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGet,
  getSinglePeriodPeriodMePeriodIdGet,
  getSingleReadingTempMeTemperatureIdGet,
  getSingleSymptomEventSymptomsMeSymptomIdGet,
  getSymptomEventsSymptomsGet,
  getTempReadingsTempGet,
  getUsersUsersGet,
  healthCheckHealthGet,
  loginAuthPost,
  type Options,
  readMeUsersMeGet,
  refreshTokensAuthRefreshPost,
  removePartnerUsersMePartnersPartnerIdDelete,
  rootGet,
  updateMeUsersMePatch,
  updatePeriodPeriodMePeriodIdPatch,
  updateReadingTempMeTemperatureIdPatch,
  updateSymptomEventSymptomsMeSymptomIdPatch,
} from '../sdk.gen';
import type {
  AddPartnerUsersMePartnersPartnerIdPostData,
  AddPartnerUsersMePartnersPartnerIdPostError,
  AddPartnerUsersMePartnersPartnerIdPostResponse,
  CreatePeriodEventPeriodPostData,
  CreatePeriodEventPeriodPostError,
  CreatePeriodEventPeriodPostResponse,
  CreateSymptomEventSymptomsPostData,
  CreateSymptomEventSymptomsPostError,
  CreateSymptomEventSymptomsPostResponse,
  CreateTempReadingTempPostData,
  CreateTempReadingTempPostError,
  CreateTempReadingTempPostResponse,
  CreateUserUsersPostData,
  CreateUserUsersPostError,
  CreateUserUsersPostResponse,
  DeleteMeUsersMeDeleteData,
  DeleteMeUsersMeDeleteResponse,
  DeletePeriodPeriodMePeriodIdDeleteData,
  DeletePeriodPeriodMePeriodIdDeleteError,
  DeletePeriodPeriodMePeriodIdDeleteResponse,
  DeleteSymptomEventSymptomsMeSymptomIdDeleteData,
  DeleteSymptomEventSymptomsMeSymptomIdDeleteError,
  DeleteSymptomEventSymptomsMeSymptomIdDeleteResponse,
  DeleteTempTempMeTemperatureIdDeleteData,
  DeleteTempTempMeTemperatureIdDeleteError,
  DeleteTempTempMeTemperatureIdDeleteResponse,
  ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData,
  ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetError,
  ExportSymptomsCsvSymptomsMeCsvGetData,
  ExportSymptomsCsvSymptomsMeCsvGetError,
  GetAllPeriodsPeriodGetData,
  GetAllPeriodsPeriodGetError,
  GetAllPeriodsPeriodGetResponse,
  GetMyEventsCsvUsersMeEventsCsvGetData,
  GetMyEventsCsvUsersMeEventsCsvGetError,
  GetMyEventsUsersMeEventsGetData,
  GetMyEventsUsersMeEventsGetError,
  GetMyEventsUsersMeEventsGetResponse,
  GetMyPartnersUsersMePartnersGetData,
  GetMyPartnersUsersMePartnersGetResponse,
  GetMyPeriodsCsvPeriodMeCsvGetData,
  GetMyPeriodsCsvPeriodMeCsvGetError,
  GetMyPeriodsPeriodMeGetData,
  GetMyPeriodsPeriodMeGetError,
  GetMyPeriodsPeriodMeGetResponse,
  GetMyReadingsTempMeGetData,
  GetMyReadingsTempMeGetError,
  GetMyReadingsTempMeGetResponse,
  GetMySymptomEventsSymptomsMeGetData,
  GetMySymptomEventsSymptomsMeGetError,
  GetMySymptomEventsSymptomsMeGetResponse,
  GetMyTempAveragesTempMeAveragesGetData,
  GetMyTempAveragesTempMeAveragesGetError,
  GetMyTempAveragesTempMeAveragesGetResponse,
  GetMyTempReadingsCsvTempMeCsvGetData,
  GetMyTempReadingsCsvTempMeCsvGetError,
  GetNextPeriodPeriodMeNextGetData,
  GetNextPeriodPeriodMeNextGetResponse,
  GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData,
  GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetError,
  GetPartnerPeriodsPeriodPartnerPartnerIdGetData,
  GetPartnerPeriodsPeriodPartnerPartnerIdGetError,
  GetPartnerPeriodsPeriodPartnerPartnerIdGetResponse,
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetData,
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetError,
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponse,
  GetPartnerTemperaturesTempPartnerPartnerIdGetData,
  GetPartnerTemperaturesTempPartnerPartnerIdGetError,
  GetPartnerTemperaturesTempPartnerPartnerIdGetResponse,
  GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData,
  GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetError,
  GetSinglePeriodPeriodMePeriodIdGetData,
  GetSinglePeriodPeriodMePeriodIdGetError,
  GetSinglePeriodPeriodMePeriodIdGetResponse,
  GetSingleReadingTempMeTemperatureIdGetData,
  GetSingleReadingTempMeTemperatureIdGetError,
  GetSingleReadingTempMeTemperatureIdGetResponse,
  GetSingleSymptomEventSymptomsMeSymptomIdGetData,
  GetSingleSymptomEventSymptomsMeSymptomIdGetError,
  GetSingleSymptomEventSymptomsMeSymptomIdGetResponse,
  GetSymptomEventsSymptomsGetData,
  GetSymptomEventsSymptomsGetError,
  GetSymptomEventsSymptomsGetResponse,
  GetTempReadingsTempGetData,
  GetTempReadingsTempGetError,
  GetTempReadingsTempGetResponse,
  GetUsersUsersGetData,
  GetUsersUsersGetError,
  GetUsersUsersGetResponse,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponse,
  LoginAuthPostData,
  LoginAuthPostError,
  LoginAuthPostResponse,
  ReadMeUsersMeGetData,
  ReadMeUsersMeGetResponse,
  RefreshTokensAuthRefreshPostData,
  RefreshTokensAuthRefreshPostError,
  RefreshTokensAuthRefreshPostResponse,
  RemovePartnerUsersMePartnersPartnerIdDeleteData,
  RemovePartnerUsersMePartnersPartnerIdDeleteError,
  RemovePartnerUsersMePartnersPartnerIdDeleteResponse,
  RootGetData,
  RootGetResponse,
  UpdateMeUsersMePatchData,
  UpdateMeUsersMePatchError,
  UpdateMeUsersMePatchResponse,
  UpdatePeriodPeriodMePeriodIdPatchData,
  UpdatePeriodPeriodMePeriodIdPatchError,
  UpdatePeriodPeriodMePeriodIdPatchResponse,
  UpdateReadingTempMeTemperatureIdPatchData,
  UpdateReadingTempMeTemperatureIdPatchError,
  UpdateReadingTempMeTemperatureIdPatchResponse,
  UpdateSymptomEventSymptomsMeSymptomIdPatchData,
  UpdateSymptomEventSymptomsMeSymptomIdPatchError,
  UpdateSymptomEventSymptomsMeSymptomIdPatchResponse,
} from '../types.gen';

/**
 * Login
 */
export const loginAuthPostMutation = (
  options?: Partial<Options<LoginAuthPostData>>,
): UseMutationOptions<
  LoginAuthPostResponse,
  LoginAuthPostError,
  Options<LoginAuthPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginAuthPostResponse,
    LoginAuthPostError,
    Options<LoginAuthPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await loginAuthPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh Tokens
 */
export const refreshTokensAuthRefreshPostMutation = (
  options?: Partial<Options<RefreshTokensAuthRefreshPostData>>,
): UseMutationOptions<
  RefreshTokensAuthRefreshPostResponse,
  RefreshTokensAuthRefreshPostError,
  Options<RefreshTokensAuthRefreshPostData>
> => {
  const mutationOptions: UseMutationOptions<
    RefreshTokensAuthRefreshPostResponse,
    RefreshTokensAuthRefreshPostError,
    Options<RefreshTokensAuthRefreshPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshTokensAuthRefreshPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getUsersUsersGetQueryKey = (options?: Options<GetUsersUsersGetData>) =>
  createQueryKey('getUsersUsersGet', options);

/**
 * Get Users
 *
 * Endpoint to retrieve users for admin moderation. Admin-only.
 *
 * :return: A list of safe user representations (sans sensitive info)
 * :rtype: Sequence[UserSafe]
 */
export const getUsersUsersGetOptions = (options?: Options<GetUsersUsersGetData>) =>
  queryOptions<
    GetUsersUsersGetResponse,
    GetUsersUsersGetError,
    GetUsersUsersGetResponse,
    ReturnType<typeof getUsersUsersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsersUsersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersUsersGetQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getUsersUsersGetInfiniteQueryKey = (
  options?: Options<GetUsersUsersGetData>,
): QueryKey<Options<GetUsersUsersGetData>> =>
  createQueryKey('getUsersUsersGet', options, true);

/**
 * Get Users
 *
 * Endpoint to retrieve users for admin moderation. Admin-only.
 *
 * :return: A list of safe user representations (sans sensitive info)
 * :rtype: Sequence[UserSafe]
 */
export const getUsersUsersGetInfiniteOptions = (
  options?: Options<GetUsersUsersGetData>,
) =>
  infiniteQueryOptions<
    GetUsersUsersGetResponse,
    GetUsersUsersGetError,
    InfiniteData<GetUsersUsersGetResponse>,
    QueryKey<Options<GetUsersUsersGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetUsersUsersGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetUsersUsersGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getUsersUsersGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getUsersUsersGetInfiniteQueryKey(options),
    },
  );

/**
 * Create User
 */
export const createUserUsersPostMutation = (
  options?: Partial<Options<CreateUserUsersPostData>>,
): UseMutationOptions<
  CreateUserUsersPostResponse,
  CreateUserUsersPostError,
  Options<CreateUserUsersPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserUsersPostResponse,
    CreateUserUsersPostError,
    Options<CreateUserUsersPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUserUsersPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Me
 */
export const deleteMeUsersMeDeleteMutation = (
  options?: Partial<Options<DeleteMeUsersMeDeleteData>>,
): UseMutationOptions<
  DeleteMeUsersMeDeleteResponse,
  DefaultError,
  Options<DeleteMeUsersMeDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteMeUsersMeDeleteResponse,
    DefaultError,
    Options<DeleteMeUsersMeDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteMeUsersMeDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const readMeUsersMeGetQueryKey = (options?: Options<ReadMeUsersMeGetData>) =>
  createQueryKey('readMeUsersMeGet', options);

/**
 * Read Me
 */
export const readMeUsersMeGetOptions = (options?: Options<ReadMeUsersMeGetData>) =>
  queryOptions<
    ReadMeUsersMeGetResponse,
    DefaultError,
    ReadMeUsersMeGetResponse,
    ReturnType<typeof readMeUsersMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readMeUsersMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readMeUsersMeGetQueryKey(options),
  });

/**
 * Update Me
 */
export const updateMeUsersMePatchMutation = (
  options?: Partial<Options<UpdateMeUsersMePatchData>>,
): UseMutationOptions<
  UpdateMeUsersMePatchResponse,
  UpdateMeUsersMePatchError,
  Options<UpdateMeUsersMePatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateMeUsersMePatchResponse,
    UpdateMeUsersMePatchError,
    Options<UpdateMeUsersMePatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateMeUsersMePatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMyEventsUsersMeEventsGetQueryKey = (
  options?: Options<GetMyEventsUsersMeEventsGetData>,
) => createQueryKey('getMyEventsUsersMeEventsGet', options);

/**
 * Get My Events
 */
export const getMyEventsUsersMeEventsGetOptions = (
  options?: Options<GetMyEventsUsersMeEventsGetData>,
) =>
  queryOptions<
    GetMyEventsUsersMeEventsGetResponse,
    GetMyEventsUsersMeEventsGetError,
    GetMyEventsUsersMeEventsGetResponse,
    ReturnType<typeof getMyEventsUsersMeEventsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyEventsUsersMeEventsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyEventsUsersMeEventsGetQueryKey(options),
  });

export const getMyEventsUsersMeEventsGetInfiniteQueryKey = (
  options?: Options<GetMyEventsUsersMeEventsGetData>,
): QueryKey<Options<GetMyEventsUsersMeEventsGetData>> =>
  createQueryKey('getMyEventsUsersMeEventsGet', options, true);

/**
 * Get My Events
 */
export const getMyEventsUsersMeEventsGetInfiniteOptions = (
  options?: Options<GetMyEventsUsersMeEventsGetData>,
) =>
  infiniteQueryOptions<
    GetMyEventsUsersMeEventsGetResponse,
    GetMyEventsUsersMeEventsGetError,
    InfiniteData<GetMyEventsUsersMeEventsGetResponse>,
    QueryKey<Options<GetMyEventsUsersMeEventsGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetMyEventsUsersMeEventsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMyEventsUsersMeEventsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMyEventsUsersMeEventsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMyEventsUsersMeEventsGetInfiniteQueryKey(options),
    },
  );

export const getMyEventsCsvUsersMeEventsCsvGetQueryKey = (
  options?: Options<GetMyEventsCsvUsersMeEventsCsvGetData>,
) => createQueryKey('getMyEventsCsvUsersMeEventsCsvGet', options);

/**
 * Get My Events Csv
 */
export const getMyEventsCsvUsersMeEventsCsvGetOptions = (
  options?: Options<GetMyEventsCsvUsersMeEventsCsvGetData>,
) =>
  queryOptions<
    unknown,
    GetMyEventsCsvUsersMeEventsCsvGetError,
    unknown,
    ReturnType<typeof getMyEventsCsvUsersMeEventsCsvGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyEventsCsvUsersMeEventsCsvGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyEventsCsvUsersMeEventsCsvGetQueryKey(options),
  });

export const getMyEventsCsvUsersMeEventsCsvGetInfiniteQueryKey = (
  options?: Options<GetMyEventsCsvUsersMeEventsCsvGetData>,
): QueryKey<Options<GetMyEventsCsvUsersMeEventsCsvGetData>> =>
  createQueryKey('getMyEventsCsvUsersMeEventsCsvGet', options, true);

/**
 * Get My Events Csv
 */
export const getMyEventsCsvUsersMeEventsCsvGetInfiniteOptions = (
  options?: Options<GetMyEventsCsvUsersMeEventsCsvGetData>,
) =>
  infiniteQueryOptions<
    unknown,
    GetMyEventsCsvUsersMeEventsCsvGetError,
    InfiniteData<unknown>,
    QueryKey<Options<GetMyEventsCsvUsersMeEventsCsvGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetMyEventsCsvUsersMeEventsCsvGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMyEventsCsvUsersMeEventsCsvGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMyEventsCsvUsersMeEventsCsvGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMyEventsCsvUsersMeEventsCsvGetInfiniteQueryKey(options),
    },
  );

export const getMyPartnersUsersMePartnersGetQueryKey = (
  options?: Options<GetMyPartnersUsersMePartnersGetData>,
) => createQueryKey('getMyPartnersUsersMePartnersGet', options);

/**
 * Get My Partners
 */
export const getMyPartnersUsersMePartnersGetOptions = (
  options?: Options<GetMyPartnersUsersMePartnersGetData>,
) =>
  queryOptions<
    GetMyPartnersUsersMePartnersGetResponse,
    DefaultError,
    GetMyPartnersUsersMePartnersGetResponse,
    ReturnType<typeof getMyPartnersUsersMePartnersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyPartnersUsersMePartnersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyPartnersUsersMePartnersGetQueryKey(options),
  });

/**
 * Remove Partner
 */
export const removePartnerUsersMePartnersPartnerIdDeleteMutation = (
  options?: Partial<Options<RemovePartnerUsersMePartnersPartnerIdDeleteData>>,
): UseMutationOptions<
  RemovePartnerUsersMePartnersPartnerIdDeleteResponse,
  RemovePartnerUsersMePartnersPartnerIdDeleteError,
  Options<RemovePartnerUsersMePartnersPartnerIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    RemovePartnerUsersMePartnersPartnerIdDeleteResponse,
    RemovePartnerUsersMePartnersPartnerIdDeleteError,
    Options<RemovePartnerUsersMePartnersPartnerIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removePartnerUsersMePartnersPartnerIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Add Partner
 */
export const addPartnerUsersMePartnersPartnerIdPostMutation = (
  options?: Partial<Options<AddPartnerUsersMePartnersPartnerIdPostData>>,
): UseMutationOptions<
  AddPartnerUsersMePartnersPartnerIdPostResponse,
  AddPartnerUsersMePartnersPartnerIdPostError,
  Options<AddPartnerUsersMePartnersPartnerIdPostData>
> => {
  const mutationOptions: UseMutationOptions<
    AddPartnerUsersMePartnersPartnerIdPostResponse,
    AddPartnerUsersMePartnersPartnerIdPostError,
    Options<AddPartnerUsersMePartnersPartnerIdPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await addPartnerUsersMePartnersPartnerIdPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAllPeriodsPeriodGetQueryKey = (
  options?: Options<GetAllPeriodsPeriodGetData>,
) => createQueryKey('getAllPeriodsPeriodGet', options);

/**
 * Get All Periods
 */
export const getAllPeriodsPeriodGetOptions = (
  options?: Options<GetAllPeriodsPeriodGetData>,
) =>
  queryOptions<
    GetAllPeriodsPeriodGetResponse,
    GetAllPeriodsPeriodGetError,
    GetAllPeriodsPeriodGetResponse,
    ReturnType<typeof getAllPeriodsPeriodGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllPeriodsPeriodGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllPeriodsPeriodGetQueryKey(options),
  });

export const getAllPeriodsPeriodGetInfiniteQueryKey = (
  options?: Options<GetAllPeriodsPeriodGetData>,
): QueryKey<Options<GetAllPeriodsPeriodGetData>> =>
  createQueryKey('getAllPeriodsPeriodGet', options, true);

/**
 * Get All Periods
 */
export const getAllPeriodsPeriodGetInfiniteOptions = (
  options?: Options<GetAllPeriodsPeriodGetData>,
) =>
  infiniteQueryOptions<
    GetAllPeriodsPeriodGetResponse,
    GetAllPeriodsPeriodGetError,
    InfiniteData<GetAllPeriodsPeriodGetResponse>,
    QueryKey<Options<GetAllPeriodsPeriodGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetAllPeriodsPeriodGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAllPeriodsPeriodGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAllPeriodsPeriodGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getAllPeriodsPeriodGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Period Event
 */
export const createPeriodEventPeriodPostMutation = (
  options?: Partial<Options<CreatePeriodEventPeriodPostData>>,
): UseMutationOptions<
  CreatePeriodEventPeriodPostResponse,
  CreatePeriodEventPeriodPostError,
  Options<CreatePeriodEventPeriodPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreatePeriodEventPeriodPostResponse,
    CreatePeriodEventPeriodPostError,
    Options<CreatePeriodEventPeriodPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createPeriodEventPeriodPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMyPeriodsPeriodMeGetQueryKey = (
  options?: Options<GetMyPeriodsPeriodMeGetData>,
) => createQueryKey('getMyPeriodsPeriodMeGet', options);

/**
 * Get My Periods
 */
export const getMyPeriodsPeriodMeGetOptions = (
  options?: Options<GetMyPeriodsPeriodMeGetData>,
) =>
  queryOptions<
    GetMyPeriodsPeriodMeGetResponse,
    GetMyPeriodsPeriodMeGetError,
    GetMyPeriodsPeriodMeGetResponse,
    ReturnType<typeof getMyPeriodsPeriodMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyPeriodsPeriodMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyPeriodsPeriodMeGetQueryKey(options),
  });

export const getMyPeriodsPeriodMeGetInfiniteQueryKey = (
  options?: Options<GetMyPeriodsPeriodMeGetData>,
): QueryKey<Options<GetMyPeriodsPeriodMeGetData>> =>
  createQueryKey('getMyPeriodsPeriodMeGet', options, true);

/**
 * Get My Periods
 */
export const getMyPeriodsPeriodMeGetInfiniteOptions = (
  options?: Options<GetMyPeriodsPeriodMeGetData>,
) =>
  infiniteQueryOptions<
    GetMyPeriodsPeriodMeGetResponse,
    GetMyPeriodsPeriodMeGetError,
    InfiniteData<GetMyPeriodsPeriodMeGetResponse>,
    QueryKey<Options<GetMyPeriodsPeriodMeGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetMyPeriodsPeriodMeGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMyPeriodsPeriodMeGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMyPeriodsPeriodMeGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMyPeriodsPeriodMeGetInfiniteQueryKey(options),
    },
  );

/**
 * Delete Period
 */
export const deletePeriodPeriodMePeriodIdDeleteMutation = (
  options?: Partial<Options<DeletePeriodPeriodMePeriodIdDeleteData>>,
): UseMutationOptions<
  DeletePeriodPeriodMePeriodIdDeleteResponse,
  DeletePeriodPeriodMePeriodIdDeleteError,
  Options<DeletePeriodPeriodMePeriodIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeletePeriodPeriodMePeriodIdDeleteResponse,
    DeletePeriodPeriodMePeriodIdDeleteError,
    Options<DeletePeriodPeriodMePeriodIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deletePeriodPeriodMePeriodIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSinglePeriodPeriodMePeriodIdGetQueryKey = (
  options: Options<GetSinglePeriodPeriodMePeriodIdGetData>,
) => createQueryKey('getSinglePeriodPeriodMePeriodIdGet', options);

/**
 * Get Single Period
 */
export const getSinglePeriodPeriodMePeriodIdGetOptions = (
  options: Options<GetSinglePeriodPeriodMePeriodIdGetData>,
) =>
  queryOptions<
    GetSinglePeriodPeriodMePeriodIdGetResponse,
    GetSinglePeriodPeriodMePeriodIdGetError,
    GetSinglePeriodPeriodMePeriodIdGetResponse,
    ReturnType<typeof getSinglePeriodPeriodMePeriodIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSinglePeriodPeriodMePeriodIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSinglePeriodPeriodMePeriodIdGetQueryKey(options),
  });

/**
 * Update Period
 */
export const updatePeriodPeriodMePeriodIdPatchMutation = (
  options?: Partial<Options<UpdatePeriodPeriodMePeriodIdPatchData>>,
): UseMutationOptions<
  UpdatePeriodPeriodMePeriodIdPatchResponse,
  UpdatePeriodPeriodMePeriodIdPatchError,
  Options<UpdatePeriodPeriodMePeriodIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdatePeriodPeriodMePeriodIdPatchResponse,
    UpdatePeriodPeriodMePeriodIdPatchError,
    Options<UpdatePeriodPeriodMePeriodIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updatePeriodPeriodMePeriodIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMyPeriodsCsvPeriodMeCsvGetQueryKey = (
  options?: Options<GetMyPeriodsCsvPeriodMeCsvGetData>,
) => createQueryKey('getMyPeriodsCsvPeriodMeCsvGet', options);

/**
 * Get My Periods Csv
 */
export const getMyPeriodsCsvPeriodMeCsvGetOptions = (
  options?: Options<GetMyPeriodsCsvPeriodMeCsvGetData>,
) =>
  queryOptions<
    unknown,
    GetMyPeriodsCsvPeriodMeCsvGetError,
    unknown,
    ReturnType<typeof getMyPeriodsCsvPeriodMeCsvGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyPeriodsCsvPeriodMeCsvGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyPeriodsCsvPeriodMeCsvGetQueryKey(options),
  });

export const getMyPeriodsCsvPeriodMeCsvGetInfiniteQueryKey = (
  options?: Options<GetMyPeriodsCsvPeriodMeCsvGetData>,
): QueryKey<Options<GetMyPeriodsCsvPeriodMeCsvGetData>> =>
  createQueryKey('getMyPeriodsCsvPeriodMeCsvGet', options, true);

/**
 * Get My Periods Csv
 */
export const getMyPeriodsCsvPeriodMeCsvGetInfiniteOptions = (
  options?: Options<GetMyPeriodsCsvPeriodMeCsvGetData>,
) =>
  infiniteQueryOptions<
    unknown,
    GetMyPeriodsCsvPeriodMeCsvGetError,
    InfiniteData<unknown>,
    QueryKey<Options<GetMyPeriodsCsvPeriodMeCsvGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetMyPeriodsCsvPeriodMeCsvGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMyPeriodsCsvPeriodMeCsvGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMyPeriodsCsvPeriodMeCsvGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMyPeriodsCsvPeriodMeCsvGetInfiniteQueryKey(options),
    },
  );

export const getNextPeriodPeriodMeNextGetQueryKey = (
  options?: Options<GetNextPeriodPeriodMeNextGetData>,
) => createQueryKey('getNextPeriodPeriodMeNextGet', options);

/**
 * Get Next Period
 */
export const getNextPeriodPeriodMeNextGetOptions = (
  options?: Options<GetNextPeriodPeriodMeNextGetData>,
) =>
  queryOptions<
    GetNextPeriodPeriodMeNextGetResponse,
    DefaultError,
    GetNextPeriodPeriodMeNextGetResponse,
    ReturnType<typeof getNextPeriodPeriodMeNextGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNextPeriodPeriodMeNextGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNextPeriodPeriodMeNextGetQueryKey(options),
  });

export const getPartnerPeriodsPeriodPartnerPartnerIdGetQueryKey = (
  options: Options<GetPartnerPeriodsPeriodPartnerPartnerIdGetData>,
) => createQueryKey('getPartnerPeriodsPeriodPartnerPartnerIdGet', options);

/**
 * Get Partner Periods
 */
export const getPartnerPeriodsPeriodPartnerPartnerIdGetOptions = (
  options: Options<GetPartnerPeriodsPeriodPartnerPartnerIdGetData>,
) =>
  queryOptions<
    GetPartnerPeriodsPeriodPartnerPartnerIdGetResponse,
    GetPartnerPeriodsPeriodPartnerPartnerIdGetError,
    GetPartnerPeriodsPeriodPartnerPartnerIdGetResponse,
    ReturnType<typeof getPartnerPeriodsPeriodPartnerPartnerIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPartnerPeriodsPeriodPartnerPartnerIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPartnerPeriodsPeriodPartnerPartnerIdGetQueryKey(options),
  });

export const getPartnerPeriodsPeriodPartnerPartnerIdGetInfiniteQueryKey = (
  options: Options<GetPartnerPeriodsPeriodPartnerPartnerIdGetData>,
): QueryKey<Options<GetPartnerPeriodsPeriodPartnerPartnerIdGetData>> =>
  createQueryKey('getPartnerPeriodsPeriodPartnerPartnerIdGet', options, true);

/**
 * Get Partner Periods
 */
export const getPartnerPeriodsPeriodPartnerPartnerIdGetInfiniteOptions = (
  options: Options<GetPartnerPeriodsPeriodPartnerPartnerIdGetData>,
) =>
  infiniteQueryOptions<
    GetPartnerPeriodsPeriodPartnerPartnerIdGetResponse,
    GetPartnerPeriodsPeriodPartnerPartnerIdGetError,
    InfiniteData<GetPartnerPeriodsPeriodPartnerPartnerIdGetResponse>,
    QueryKey<Options<GetPartnerPeriodsPeriodPartnerPartnerIdGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetPartnerPeriodsPeriodPartnerPartnerIdGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetPartnerPeriodsPeriodPartnerPartnerIdGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPartnerPeriodsPeriodPartnerPartnerIdGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getPartnerPeriodsPeriodPartnerPartnerIdGetInfiniteQueryKey(options),
    },
  );

export const getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetQueryKey = (
  options: Options<GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData>,
) => createQueryKey('getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGet', options);

/**
 * Get Partner Periods Csv
 */
export const getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetOptions = (
  options: Options<GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData>,
) =>
  queryOptions<
    unknown,
    GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetError,
    unknown,
    ReturnType<typeof getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetQueryKey(options),
  });

export const getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetInfiniteQueryKey = (
  options: Options<GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData>,
): QueryKey<Options<GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData>> =>
  createQueryKey('getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGet', options, true);

/**
 * Get Partner Periods Csv
 */
export const getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetInfiniteOptions = (
  options: Options<GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData>,
) =>
  infiniteQueryOptions<
    unknown,
    GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetError,
    InfiniteData<unknown>,
    QueryKey<Options<GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetInfiniteQueryKey(options),
    },
  );

export const getTempReadingsTempGetQueryKey = (
  options?: Options<GetTempReadingsTempGetData>,
) => createQueryKey('getTempReadingsTempGet', options);

/**
 * Get Temp Readings
 */
export const getTempReadingsTempGetOptions = (
  options?: Options<GetTempReadingsTempGetData>,
) =>
  queryOptions<
    GetTempReadingsTempGetResponse,
    GetTempReadingsTempGetError,
    GetTempReadingsTempGetResponse,
    ReturnType<typeof getTempReadingsTempGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTempReadingsTempGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTempReadingsTempGetQueryKey(options),
  });

export const getTempReadingsTempGetInfiniteQueryKey = (
  options?: Options<GetTempReadingsTempGetData>,
): QueryKey<Options<GetTempReadingsTempGetData>> =>
  createQueryKey('getTempReadingsTempGet', options, true);

/**
 * Get Temp Readings
 */
export const getTempReadingsTempGetInfiniteOptions = (
  options?: Options<GetTempReadingsTempGetData>,
) =>
  infiniteQueryOptions<
    GetTempReadingsTempGetResponse,
    GetTempReadingsTempGetError,
    InfiniteData<GetTempReadingsTempGetResponse>,
    QueryKey<Options<GetTempReadingsTempGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetTempReadingsTempGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetTempReadingsTempGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getTempReadingsTempGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getTempReadingsTempGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Temp Reading
 */
export const createTempReadingTempPostMutation = (
  options?: Partial<Options<CreateTempReadingTempPostData>>,
): UseMutationOptions<
  CreateTempReadingTempPostResponse,
  CreateTempReadingTempPostError,
  Options<CreateTempReadingTempPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTempReadingTempPostResponse,
    CreateTempReadingTempPostError,
    Options<CreateTempReadingTempPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTempReadingTempPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMyReadingsTempMeGetQueryKey = (
  options?: Options<GetMyReadingsTempMeGetData>,
) => createQueryKey('getMyReadingsTempMeGet', options);

/**
 * Get My Readings
 */
export const getMyReadingsTempMeGetOptions = (
  options?: Options<GetMyReadingsTempMeGetData>,
) =>
  queryOptions<
    GetMyReadingsTempMeGetResponse,
    GetMyReadingsTempMeGetError,
    GetMyReadingsTempMeGetResponse,
    ReturnType<typeof getMyReadingsTempMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyReadingsTempMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyReadingsTempMeGetQueryKey(options),
  });

export const getMyReadingsTempMeGetInfiniteQueryKey = (
  options?: Options<GetMyReadingsTempMeGetData>,
): QueryKey<Options<GetMyReadingsTempMeGetData>> =>
  createQueryKey('getMyReadingsTempMeGet', options, true);

/**
 * Get My Readings
 */
export const getMyReadingsTempMeGetInfiniteOptions = (
  options?: Options<GetMyReadingsTempMeGetData>,
) =>
  infiniteQueryOptions<
    GetMyReadingsTempMeGetResponse,
    GetMyReadingsTempMeGetError,
    InfiniteData<GetMyReadingsTempMeGetResponse>,
    QueryKey<Options<GetMyReadingsTempMeGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetMyReadingsTempMeGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMyReadingsTempMeGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMyReadingsTempMeGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMyReadingsTempMeGetInfiniteQueryKey(options),
    },
  );

/**
 * Delete Temp
 */
export const deleteTempTempMeTemperatureIdDeleteMutation = (
  options?: Partial<Options<DeleteTempTempMeTemperatureIdDeleteData>>,
): UseMutationOptions<
  DeleteTempTempMeTemperatureIdDeleteResponse,
  DeleteTempTempMeTemperatureIdDeleteError,
  Options<DeleteTempTempMeTemperatureIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTempTempMeTemperatureIdDeleteResponse,
    DeleteTempTempMeTemperatureIdDeleteError,
    Options<DeleteTempTempMeTemperatureIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTempTempMeTemperatureIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSingleReadingTempMeTemperatureIdGetQueryKey = (
  options: Options<GetSingleReadingTempMeTemperatureIdGetData>,
) => createQueryKey('getSingleReadingTempMeTemperatureIdGet', options);

/**
 * Get Single Reading
 */
export const getSingleReadingTempMeTemperatureIdGetOptions = (
  options: Options<GetSingleReadingTempMeTemperatureIdGetData>,
) =>
  queryOptions<
    GetSingleReadingTempMeTemperatureIdGetResponse,
    GetSingleReadingTempMeTemperatureIdGetError,
    GetSingleReadingTempMeTemperatureIdGetResponse,
    ReturnType<typeof getSingleReadingTempMeTemperatureIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSingleReadingTempMeTemperatureIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSingleReadingTempMeTemperatureIdGetQueryKey(options),
  });

/**
 * Update Reading
 */
export const updateReadingTempMeTemperatureIdPatchMutation = (
  options?: Partial<Options<UpdateReadingTempMeTemperatureIdPatchData>>,
): UseMutationOptions<
  UpdateReadingTempMeTemperatureIdPatchResponse,
  UpdateReadingTempMeTemperatureIdPatchError,
  Options<UpdateReadingTempMeTemperatureIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateReadingTempMeTemperatureIdPatchResponse,
    UpdateReadingTempMeTemperatureIdPatchError,
    Options<UpdateReadingTempMeTemperatureIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateReadingTempMeTemperatureIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMyTempAveragesTempMeAveragesGetQueryKey = (
  options?: Options<GetMyTempAveragesTempMeAveragesGetData>,
) => createQueryKey('getMyTempAveragesTempMeAveragesGet', options);

/**
 * Get My Temp Averages
 */
export const getMyTempAveragesTempMeAveragesGetOptions = (
  options?: Options<GetMyTempAveragesTempMeAveragesGetData>,
) =>
  queryOptions<
    GetMyTempAveragesTempMeAveragesGetResponse,
    GetMyTempAveragesTempMeAveragesGetError,
    GetMyTempAveragesTempMeAveragesGetResponse,
    ReturnType<typeof getMyTempAveragesTempMeAveragesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyTempAveragesTempMeAveragesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyTempAveragesTempMeAveragesGetQueryKey(options),
  });

export const getMyTempAveragesTempMeAveragesGetInfiniteQueryKey = (
  options?: Options<GetMyTempAveragesTempMeAveragesGetData>,
): QueryKey<Options<GetMyTempAveragesTempMeAveragesGetData>> =>
  createQueryKey('getMyTempAveragesTempMeAveragesGet', options, true);

/**
 * Get My Temp Averages
 */
export const getMyTempAveragesTempMeAveragesGetInfiniteOptions = (
  options?: Options<GetMyTempAveragesTempMeAveragesGetData>,
) =>
  infiniteQueryOptions<
    GetMyTempAveragesTempMeAveragesGetResponse,
    GetMyTempAveragesTempMeAveragesGetError,
    InfiniteData<GetMyTempAveragesTempMeAveragesGetResponse>,
    QueryKey<Options<GetMyTempAveragesTempMeAveragesGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetMyTempAveragesTempMeAveragesGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMyTempAveragesTempMeAveragesGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMyTempAveragesTempMeAveragesGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMyTempAveragesTempMeAveragesGetInfiniteQueryKey(options),
    },
  );

export const getMyTempReadingsCsvTempMeCsvGetQueryKey = (
  options?: Options<GetMyTempReadingsCsvTempMeCsvGetData>,
) => createQueryKey('getMyTempReadingsCsvTempMeCsvGet', options);

/**
 * Get My Temp Readings Csv
 */
export const getMyTempReadingsCsvTempMeCsvGetOptions = (
  options?: Options<GetMyTempReadingsCsvTempMeCsvGetData>,
) =>
  queryOptions<
    unknown,
    GetMyTempReadingsCsvTempMeCsvGetError,
    unknown,
    ReturnType<typeof getMyTempReadingsCsvTempMeCsvGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMyTempReadingsCsvTempMeCsvGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMyTempReadingsCsvTempMeCsvGetQueryKey(options),
  });

export const getMyTempReadingsCsvTempMeCsvGetInfiniteQueryKey = (
  options?: Options<GetMyTempReadingsCsvTempMeCsvGetData>,
): QueryKey<Options<GetMyTempReadingsCsvTempMeCsvGetData>> =>
  createQueryKey('getMyTempReadingsCsvTempMeCsvGet', options, true);

/**
 * Get My Temp Readings Csv
 */
export const getMyTempReadingsCsvTempMeCsvGetInfiniteOptions = (
  options?: Options<GetMyTempReadingsCsvTempMeCsvGetData>,
) =>
  infiniteQueryOptions<
    unknown,
    GetMyTempReadingsCsvTempMeCsvGetError,
    InfiniteData<unknown>,
    QueryKey<Options<GetMyTempReadingsCsvTempMeCsvGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetMyTempReadingsCsvTempMeCsvGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMyTempReadingsCsvTempMeCsvGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMyTempReadingsCsvTempMeCsvGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMyTempReadingsCsvTempMeCsvGetInfiniteQueryKey(options),
    },
  );

export const getPartnerTemperaturesTempPartnerPartnerIdGetQueryKey = (
  options: Options<GetPartnerTemperaturesTempPartnerPartnerIdGetData>,
) => createQueryKey('getPartnerTemperaturesTempPartnerPartnerIdGet', options);

/**
 * Get Partner Temperatures
 */
export const getPartnerTemperaturesTempPartnerPartnerIdGetOptions = (
  options: Options<GetPartnerTemperaturesTempPartnerPartnerIdGetData>,
) =>
  queryOptions<
    GetPartnerTemperaturesTempPartnerPartnerIdGetResponse,
    GetPartnerTemperaturesTempPartnerPartnerIdGetError,
    GetPartnerTemperaturesTempPartnerPartnerIdGetResponse,
    ReturnType<typeof getPartnerTemperaturesTempPartnerPartnerIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPartnerTemperaturesTempPartnerPartnerIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPartnerTemperaturesTempPartnerPartnerIdGetQueryKey(options),
  });

export const getPartnerTemperaturesTempPartnerPartnerIdGetInfiniteQueryKey = (
  options: Options<GetPartnerTemperaturesTempPartnerPartnerIdGetData>,
): QueryKey<Options<GetPartnerTemperaturesTempPartnerPartnerIdGetData>> =>
  createQueryKey('getPartnerTemperaturesTempPartnerPartnerIdGet', options, true);

/**
 * Get Partner Temperatures
 */
export const getPartnerTemperaturesTempPartnerPartnerIdGetInfiniteOptions = (
  options: Options<GetPartnerTemperaturesTempPartnerPartnerIdGetData>,
) =>
  infiniteQueryOptions<
    GetPartnerTemperaturesTempPartnerPartnerIdGetResponse,
    GetPartnerTemperaturesTempPartnerPartnerIdGetError,
    InfiniteData<GetPartnerTemperaturesTempPartnerPartnerIdGetResponse>,
    QueryKey<Options<GetPartnerTemperaturesTempPartnerPartnerIdGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetPartnerTemperaturesTempPartnerPartnerIdGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetPartnerTemperaturesTempPartnerPartnerIdGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPartnerTemperaturesTempPartnerPartnerIdGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getPartnerTemperaturesTempPartnerPartnerIdGetInfiniteQueryKey(options),
    },
  );

export const getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetQueryKey = (
  options: Options<GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData>,
) => createQueryKey('getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGet', options);

/**
 * Get Partner Temp Readings Csv
 */
export const getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetOptions = (
  options: Options<GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData>,
) =>
  queryOptions<
    unknown,
    GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetError,
    unknown,
    ReturnType<typeof getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetQueryKey(options),
  });

export const getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetInfiniteQueryKey = (
  options: Options<GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData>,
): QueryKey<Options<GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData>> =>
  createQueryKey('getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGet', options, true);

/**
 * Get Partner Temp Readings Csv
 */
export const getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetInfiniteOptions = (
  options: Options<GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData>,
) =>
  infiniteQueryOptions<
    unknown,
    GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetError,
    InfiniteData<unknown>,
    QueryKey<Options<GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetInfiniteQueryKey(options),
    },
  );

export const getSymptomEventsSymptomsGetQueryKey = (
  options?: Options<GetSymptomEventsSymptomsGetData>,
) => createQueryKey('getSymptomEventsSymptomsGet', options);

/**
 * Get Symptom Events
 */
export const getSymptomEventsSymptomsGetOptions = (
  options?: Options<GetSymptomEventsSymptomsGetData>,
) =>
  queryOptions<
    GetSymptomEventsSymptomsGetResponse,
    GetSymptomEventsSymptomsGetError,
    GetSymptomEventsSymptomsGetResponse,
    ReturnType<typeof getSymptomEventsSymptomsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSymptomEventsSymptomsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSymptomEventsSymptomsGetQueryKey(options),
  });

export const getSymptomEventsSymptomsGetInfiniteQueryKey = (
  options?: Options<GetSymptomEventsSymptomsGetData>,
): QueryKey<Options<GetSymptomEventsSymptomsGetData>> =>
  createQueryKey('getSymptomEventsSymptomsGet', options, true);

/**
 * Get Symptom Events
 */
export const getSymptomEventsSymptomsGetInfiniteOptions = (
  options?: Options<GetSymptomEventsSymptomsGetData>,
) =>
  infiniteQueryOptions<
    GetSymptomEventsSymptomsGetResponse,
    GetSymptomEventsSymptomsGetError,
    InfiniteData<GetSymptomEventsSymptomsGetResponse>,
    QueryKey<Options<GetSymptomEventsSymptomsGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetSymptomEventsSymptomsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetSymptomEventsSymptomsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getSymptomEventsSymptomsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getSymptomEventsSymptomsGetInfiniteQueryKey(options),
    },
  );

/**
 * Create Symptom Event
 */
export const createSymptomEventSymptomsPostMutation = (
  options?: Partial<Options<CreateSymptomEventSymptomsPostData>>,
): UseMutationOptions<
  CreateSymptomEventSymptomsPostResponse,
  CreateSymptomEventSymptomsPostError,
  Options<CreateSymptomEventSymptomsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSymptomEventSymptomsPostResponse,
    CreateSymptomEventSymptomsPostError,
    Options<CreateSymptomEventSymptomsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSymptomEventSymptomsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMySymptomEventsSymptomsMeGetQueryKey = (
  options?: Options<GetMySymptomEventsSymptomsMeGetData>,
) => createQueryKey('getMySymptomEventsSymptomsMeGet', options);

/**
 * Get My Symptom Events
 */
export const getMySymptomEventsSymptomsMeGetOptions = (
  options?: Options<GetMySymptomEventsSymptomsMeGetData>,
) =>
  queryOptions<
    GetMySymptomEventsSymptomsMeGetResponse,
    GetMySymptomEventsSymptomsMeGetError,
    GetMySymptomEventsSymptomsMeGetResponse,
    ReturnType<typeof getMySymptomEventsSymptomsMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMySymptomEventsSymptomsMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMySymptomEventsSymptomsMeGetQueryKey(options),
  });

export const getMySymptomEventsSymptomsMeGetInfiniteQueryKey = (
  options?: Options<GetMySymptomEventsSymptomsMeGetData>,
): QueryKey<Options<GetMySymptomEventsSymptomsMeGetData>> =>
  createQueryKey('getMySymptomEventsSymptomsMeGet', options, true);

/**
 * Get My Symptom Events
 */
export const getMySymptomEventsSymptomsMeGetInfiniteOptions = (
  options?: Options<GetMySymptomEventsSymptomsMeGetData>,
) =>
  infiniteQueryOptions<
    GetMySymptomEventsSymptomsMeGetResponse,
    GetMySymptomEventsSymptomsMeGetError,
    InfiniteData<GetMySymptomEventsSymptomsMeGetResponse>,
    QueryKey<Options<GetMySymptomEventsSymptomsMeGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetMySymptomEventsSymptomsMeGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetMySymptomEventsSymptomsMeGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getMySymptomEventsSymptomsMeGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getMySymptomEventsSymptomsMeGetInfiniteQueryKey(options),
    },
  );

/**
 * Delete Symptom Event
 */
export const deleteSymptomEventSymptomsMeSymptomIdDeleteMutation = (
  options?: Partial<Options<DeleteSymptomEventSymptomsMeSymptomIdDeleteData>>,
): UseMutationOptions<
  DeleteSymptomEventSymptomsMeSymptomIdDeleteResponse,
  DeleteSymptomEventSymptomsMeSymptomIdDeleteError,
  Options<DeleteSymptomEventSymptomsMeSymptomIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteSymptomEventSymptomsMeSymptomIdDeleteResponse,
    DeleteSymptomEventSymptomsMeSymptomIdDeleteError,
    Options<DeleteSymptomEventSymptomsMeSymptomIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteSymptomEventSymptomsMeSymptomIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSingleSymptomEventSymptomsMeSymptomIdGetQueryKey = (
  options: Options<GetSingleSymptomEventSymptomsMeSymptomIdGetData>,
) => createQueryKey('getSingleSymptomEventSymptomsMeSymptomIdGet', options);

/**
 * Get Single Symptom Event
 */
export const getSingleSymptomEventSymptomsMeSymptomIdGetOptions = (
  options: Options<GetSingleSymptomEventSymptomsMeSymptomIdGetData>,
) =>
  queryOptions<
    GetSingleSymptomEventSymptomsMeSymptomIdGetResponse,
    GetSingleSymptomEventSymptomsMeSymptomIdGetError,
    GetSingleSymptomEventSymptomsMeSymptomIdGetResponse,
    ReturnType<typeof getSingleSymptomEventSymptomsMeSymptomIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSingleSymptomEventSymptomsMeSymptomIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSingleSymptomEventSymptomsMeSymptomIdGetQueryKey(options),
  });

/**
 * Update Symptom Event
 */
export const updateSymptomEventSymptomsMeSymptomIdPatchMutation = (
  options?: Partial<Options<UpdateSymptomEventSymptomsMeSymptomIdPatchData>>,
): UseMutationOptions<
  UpdateSymptomEventSymptomsMeSymptomIdPatchResponse,
  UpdateSymptomEventSymptomsMeSymptomIdPatchError,
  Options<UpdateSymptomEventSymptomsMeSymptomIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSymptomEventSymptomsMeSymptomIdPatchResponse,
    UpdateSymptomEventSymptomsMeSymptomIdPatchError,
    Options<UpdateSymptomEventSymptomsMeSymptomIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSymptomEventSymptomsMeSymptomIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const exportSymptomsCsvSymptomsMeCsvGetQueryKey = (
  options?: Options<ExportSymptomsCsvSymptomsMeCsvGetData>,
) => createQueryKey('exportSymptomsCsvSymptomsMeCsvGet', options);

/**
 * Export Symptoms Csv
 */
export const exportSymptomsCsvSymptomsMeCsvGetOptions = (
  options?: Options<ExportSymptomsCsvSymptomsMeCsvGetData>,
) =>
  queryOptions<
    unknown,
    ExportSymptomsCsvSymptomsMeCsvGetError,
    unknown,
    ReturnType<typeof exportSymptomsCsvSymptomsMeCsvGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await exportSymptomsCsvSymptomsMeCsvGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: exportSymptomsCsvSymptomsMeCsvGetQueryKey(options),
  });

export const exportSymptomsCsvSymptomsMeCsvGetInfiniteQueryKey = (
  options?: Options<ExportSymptomsCsvSymptomsMeCsvGetData>,
): QueryKey<Options<ExportSymptomsCsvSymptomsMeCsvGetData>> =>
  createQueryKey('exportSymptomsCsvSymptomsMeCsvGet', options, true);

/**
 * Export Symptoms Csv
 */
export const exportSymptomsCsvSymptomsMeCsvGetInfiniteOptions = (
  options?: Options<ExportSymptomsCsvSymptomsMeCsvGetData>,
) =>
  infiniteQueryOptions<
    unknown,
    ExportSymptomsCsvSymptomsMeCsvGetError,
    InfiniteData<unknown>,
    QueryKey<Options<ExportSymptomsCsvSymptomsMeCsvGetData>>,
    | number
    | Pick<
        QueryKey<Options<ExportSymptomsCsvSymptomsMeCsvGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ExportSymptomsCsvSymptomsMeCsvGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await exportSymptomsCsvSymptomsMeCsvGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: exportSymptomsCsvSymptomsMeCsvGetInfiniteQueryKey(options),
    },
  );

export const getPartnerSymptomsSymptomsPartnerPartnerIdGetQueryKey = (
  options: Options<GetPartnerSymptomsSymptomsPartnerPartnerIdGetData>,
) => createQueryKey('getPartnerSymptomsSymptomsPartnerPartnerIdGet', options);

/**
 * Get Partner Symptoms
 */
export const getPartnerSymptomsSymptomsPartnerPartnerIdGetOptions = (
  options: Options<GetPartnerSymptomsSymptomsPartnerPartnerIdGetData>,
) =>
  queryOptions<
    GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponse,
    GetPartnerSymptomsSymptomsPartnerPartnerIdGetError,
    GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponse,
    ReturnType<typeof getPartnerSymptomsSymptomsPartnerPartnerIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPartnerSymptomsSymptomsPartnerPartnerIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPartnerSymptomsSymptomsPartnerPartnerIdGetQueryKey(options),
  });

export const getPartnerSymptomsSymptomsPartnerPartnerIdGetInfiniteQueryKey = (
  options: Options<GetPartnerSymptomsSymptomsPartnerPartnerIdGetData>,
): QueryKey<Options<GetPartnerSymptomsSymptomsPartnerPartnerIdGetData>> =>
  createQueryKey('getPartnerSymptomsSymptomsPartnerPartnerIdGet', options, true);

/**
 * Get Partner Symptoms
 */
export const getPartnerSymptomsSymptomsPartnerPartnerIdGetInfiniteOptions = (
  options: Options<GetPartnerSymptomsSymptomsPartnerPartnerIdGetData>,
) =>
  infiniteQueryOptions<
    GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponse,
    GetPartnerSymptomsSymptomsPartnerPartnerIdGetError,
    InfiniteData<GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponse>,
    QueryKey<Options<GetPartnerSymptomsSymptomsPartnerPartnerIdGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetPartnerSymptomsSymptomsPartnerPartnerIdGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetPartnerSymptomsSymptomsPartnerPartnerIdGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPartnerSymptomsSymptomsPartnerPartnerIdGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getPartnerSymptomsSymptomsPartnerPartnerIdGetInfiniteQueryKey(options),
    },
  );

export const exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetQueryKey = (
  options: Options<ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData>,
) => createQueryKey('exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGet', options);

/**
 * Export Partner Symptoms Csv
 */
export const exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetOptions = (
  options: Options<ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData>,
) =>
  queryOptions<
    unknown,
    ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetError,
    unknown,
    ReturnType<typeof exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetQueryKey(options),
  });

export const exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetInfiniteQueryKey = (
  options: Options<ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData>,
): QueryKey<Options<ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData>> =>
  createQueryKey('exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGet', options, true);

/**
 * Export Partner Symptoms Csv
 */
export const exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetInfiniteOptions = (
  options: Options<ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData>,
) =>
  infiniteQueryOptions<
    unknown,
    ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetError,
    InfiniteData<unknown>,
    QueryKey<Options<ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData>>,
    | number
    | Pick<
        QueryKey<Options<ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<
            Options<ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData>
          >[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetInfiniteQueryKey(options),
    },
  );

export const rootGetQueryKey = (options?: Options<RootGetData>) =>
  createQueryKey('rootGet', options);

/**
 * Root
 */
export const rootGetOptions = (options?: Options<RootGetData>) =>
  queryOptions<
    RootGetResponse,
    DefaultError,
    RootGetResponse,
    ReturnType<typeof rootGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await rootGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: rootGetQueryKey(options),
  });

export const healthCheckHealthGetQueryKey = (
  options?: Options<HealthCheckHealthGetData>,
) => createQueryKey('healthCheckHealthGet', options);

/**
 * Health Check
 */
export const healthCheckHealthGetOptions = (
  options?: Options<HealthCheckHealthGetData>,
) =>
  queryOptions<
    HealthCheckHealthGetResponse,
    DefaultError,
    HealthCheckHealthGetResponse,
    ReturnType<typeof healthCheckHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCheckHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthCheckHealthGetQueryKey(options),
  });
