// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import {
  addPartnerUsersMePartnersPartnerIdPostResponseTransformer,
  createPeriodEventPeriodPostResponseTransformer,
  createSymptomEventSymptomsPostResponseTransformer,
  createTempReadingTempPostResponseTransformer,
  getSinglePeriodPeriodMePeriodIdGetResponseTransformer,
  getSingleReadingTempMeTemperatureIdGetResponseTransformer,
  getSingleSymptomEventSymptomsMeSymptomIdGetResponseTransformer,
  healthCheckHealthGetResponseTransformer,
  readMeUsersMeGetResponseTransformer,
  updateMeUsersMePatchResponseTransformer,
  updatePeriodPeriodMePeriodIdPatchResponseTransformer,
  updateReadingTempMeTemperatureIdPatchResponseTransformer,
  updateSymptomEventSymptomsMeSymptomIdPatchResponseTransformer,
} from "./transformers.gen";
import type {
  AddPartnerUsersMePartnersPartnerIdPostData,
  AddPartnerUsersMePartnersPartnerIdPostErrors,
  AddPartnerUsersMePartnersPartnerIdPostResponses,
  CreatePeriodEventPeriodPostData,
  CreatePeriodEventPeriodPostErrors,
  CreatePeriodEventPeriodPostResponses,
  CreateSymptomEventSymptomsPostData,
  CreateSymptomEventSymptomsPostErrors,
  CreateSymptomEventSymptomsPostResponses,
  CreateTempReadingTempPostData,
  CreateTempReadingTempPostErrors,
  CreateTempReadingTempPostResponses,
  CreateUserUsersPostData,
  CreateUserUsersPostErrors,
  CreateUserUsersPostResponses,
  DeleteMeUsersMeDeleteData,
  DeleteMeUsersMeDeleteErrors,
  DeleteMeUsersMeDeleteResponses,
  DeletePeriodPeriodMePeriodIdDeleteData,
  DeletePeriodPeriodMePeriodIdDeleteErrors,
  DeletePeriodPeriodMePeriodIdDeleteResponses,
  DeleteSymptomEventSymptomsMeSymptomIdDeleteData,
  DeleteSymptomEventSymptomsMeSymptomIdDeleteErrors,
  DeleteSymptomEventSymptomsMeSymptomIdDeleteResponses,
  DeleteTempTempMeTemperatureIdDeleteData,
  DeleteTempTempMeTemperatureIdDeleteErrors,
  DeleteTempTempMeTemperatureIdDeleteResponses,
  ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData,
  ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetErrors,
  ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetResponses,
  ExportSymptomsCsvSymptomsMeCsvGetData,
  ExportSymptomsCsvSymptomsMeCsvGetErrors,
  ExportSymptomsCsvSymptomsMeCsvGetResponses,
  GetAllPeriodsPeriodGetData,
  GetAllPeriodsPeriodGetErrors,
  GetAllPeriodsPeriodGetResponses,
  GetMyEventsCsvUsersMeEventsCsvGetData,
  GetMyEventsCsvUsersMeEventsCsvGetErrors,
  GetMyEventsCsvUsersMeEventsCsvGetResponses,
  GetMyEventsUsersMeEventsGetData,
  GetMyEventsUsersMeEventsGetErrors,
  GetMyEventsUsersMeEventsGetResponses,
  GetMyPartnersUsersMePartnersGetData,
  GetMyPartnersUsersMePartnersGetErrors,
  GetMyPartnersUsersMePartnersGetResponses,
  GetMyPeriodsCsvPeriodMeCsvGetData,
  GetMyPeriodsCsvPeriodMeCsvGetErrors,
  GetMyPeriodsCsvPeriodMeCsvGetResponses,
  GetMyPeriodsPeriodMeGetData,
  GetMyPeriodsPeriodMeGetErrors,
  GetMyPeriodsPeriodMeGetResponses,
  GetMyReadingsTempMeGetData,
  GetMyReadingsTempMeGetErrors,
  GetMyReadingsTempMeGetResponses,
  GetMySymptomEventsSymptomsMeGetData,
  GetMySymptomEventsSymptomsMeGetErrors,
  GetMySymptomEventsSymptomsMeGetResponses,
  GetMyTempAveragesTempMeAveragesGetData,
  GetMyTempAveragesTempMeAveragesGetErrors,
  GetMyTempAveragesTempMeAveragesGetResponses,
  GetMyTempReadingsCsvTempMeCsvGetData,
  GetMyTempReadingsCsvTempMeCsvGetErrors,
  GetMyTempReadingsCsvTempMeCsvGetResponses,
  GetNextPeriodPeriodMeNextGetData,
  GetNextPeriodPeriodMeNextGetErrors,
  GetNextPeriodPeriodMeNextGetResponses,
  GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData,
  GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetErrors,
  GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetResponses,
  GetPartnerPeriodsPeriodPartnerPartnerIdGetData,
  GetPartnerPeriodsPeriodPartnerPartnerIdGetErrors,
  GetPartnerPeriodsPeriodPartnerPartnerIdGetResponses,
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetData,
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetErrors,
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponses,
  GetPartnerTemperaturesTempPartnerPartnerIdGetData,
  GetPartnerTemperaturesTempPartnerPartnerIdGetErrors,
  GetPartnerTemperaturesTempPartnerPartnerIdGetResponses,
  GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData,
  GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetErrors,
  GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetResponses,
  GetSinglePeriodPeriodMePeriodIdGetData,
  GetSinglePeriodPeriodMePeriodIdGetErrors,
  GetSinglePeriodPeriodMePeriodIdGetResponses,
  GetSingleReadingTempMeTemperatureIdGetData,
  GetSingleReadingTempMeTemperatureIdGetErrors,
  GetSingleReadingTempMeTemperatureIdGetResponses,
  GetSingleSymptomEventSymptomsMeSymptomIdGetData,
  GetSingleSymptomEventSymptomsMeSymptomIdGetErrors,
  GetSingleSymptomEventSymptomsMeSymptomIdGetResponses,
  GetSymptomEventsSymptomsGetData,
  GetSymptomEventsSymptomsGetErrors,
  GetSymptomEventsSymptomsGetResponses,
  GetTempReadingsTempGetData,
  GetTempReadingsTempGetErrors,
  GetTempReadingsTempGetResponses,
  GetUsersUsersGetData,
  GetUsersUsersGetErrors,
  GetUsersUsersGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  LoginAuthPostData,
  LoginAuthPostErrors,
  LoginAuthPostResponses,
  ReadMeUsersMeGetData,
  ReadMeUsersMeGetErrors,
  ReadMeUsersMeGetResponses,
  RefreshTokensAuthRefreshPostData,
  RefreshTokensAuthRefreshPostErrors,
  RefreshTokensAuthRefreshPostResponses,
  RemovePartnerUsersMePartnersPartnerIdDeleteData,
  RemovePartnerUsersMePartnersPartnerIdDeleteErrors,
  RemovePartnerUsersMePartnersPartnerIdDeleteResponses,
  RootGetData,
  RootGetResponses,
  UpdateMeUsersMePatchData,
  UpdateMeUsersMePatchErrors,
  UpdateMeUsersMePatchResponses,
  UpdatePeriodPeriodMePeriodIdPatchData,
  UpdatePeriodPeriodMePeriodIdPatchErrors,
  UpdatePeriodPeriodMePeriodIdPatchResponses,
  UpdateReadingTempMeTemperatureIdPatchData,
  UpdateReadingTempMeTemperatureIdPatchErrors,
  UpdateReadingTempMeTemperatureIdPatchResponses,
  UpdateSymptomEventSymptomsMeSymptomIdPatchData,
  UpdateSymptomEventSymptomsMeSymptomIdPatchErrors,
  UpdateSymptomEventSymptomsMeSymptomIdPatchResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const loginAuthPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginAuthPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginAuthPostResponses,
    LoginAuthPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/auth/",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Refresh Tokens
 */
export const refreshTokensAuthRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RefreshTokensAuthRefreshPostData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshTokensAuthRefreshPostResponses,
    RefreshTokensAuthRefreshPostErrors,
    ThrowOnError
  >({ url: "/auth/refresh", ...options });

/**
 * Get Users
 *
 * Endpoint to retrieve users for admin moderation. Admin-only.
 *
 * :return: A list of safe user representations (sans sensitive info)
 * :rtype: Sequence[UserSafe]
 */
export const getUsersUsersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersUsersGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetUsersUsersGetResponses,
    GetUsersUsersGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/",
    ...options,
  });

/**
 * Create User
 */
export const createUserUsersPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserUsersPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateUserUsersPostResponses,
    CreateUserUsersPostErrors,
    ThrowOnError
  >({
    url: "/users/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Me
 */
export const deleteMeUsersMeDelete = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteMeUsersMeDeleteData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteMeUsersMeDeleteResponses,
    DeleteMeUsersMeDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/",
    ...options,
  });

/**
 * Read Me
 */
export const readMeUsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadMeUsersMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReadMeUsersMeGetResponses,
    ReadMeUsersMeGetErrors,
    ThrowOnError
  >({
    responseTransformer: readMeUsersMeGetResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/",
    ...options,
  });

/**
 * Update Me
 */
export const updateMeUsersMePatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateMeUsersMePatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateMeUsersMePatchResponses,
    UpdateMeUsersMePatchErrors,
    ThrowOnError
  >({
    responseTransformer: updateMeUsersMePatchResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get My Events
 */
export const getMyEventsUsersMeEventsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMyEventsUsersMeEventsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMyEventsUsersMeEventsGetResponses,
    GetMyEventsUsersMeEventsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/events/",
    ...options,
  });

/**
 * Get My Events Csv
 */
export const getMyEventsCsvUsersMeEventsCsvGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMyEventsCsvUsersMeEventsCsvGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMyEventsCsvUsersMeEventsCsvGetResponses,
    GetMyEventsCsvUsersMeEventsCsvGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/events/csv/",
    ...options,
  });

/**
 * Get My Partners
 */
export const getMyPartnersUsersMePartnersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMyPartnersUsersMePartnersGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMyPartnersUsersMePartnersGetResponses,
    GetMyPartnersUsersMePartnersGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/partners/",
    ...options,
  });

/**
 * Remove Partner
 */
export const removePartnerUsersMePartnersPartnerIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RemovePartnerUsersMePartnersPartnerIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    RemovePartnerUsersMePartnersPartnerIdDeleteResponses,
    RemovePartnerUsersMePartnersPartnerIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/partners/{partner_id}/",
    ...options,
  });

/**
 * Add Partner
 */
export const addPartnerUsersMePartnersPartnerIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AddPartnerUsersMePartnersPartnerIdPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddPartnerUsersMePartnersPartnerIdPostResponses,
    AddPartnerUsersMePartnersPartnerIdPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      addPartnerUsersMePartnersPartnerIdPostResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me/partners/{partner_id}/",
    ...options,
  });

/**
 * Get All Periods
 */
export const getAllPeriodsPeriodGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllPeriodsPeriodGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllPeriodsPeriodGetResponses,
    GetAllPeriodsPeriodGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/",
    ...options,
  });

/**
 * Create Period Event
 */
export const createPeriodEventPeriodPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreatePeriodEventPeriodPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreatePeriodEventPeriodPostResponses,
    CreatePeriodEventPeriodPostErrors,
    ThrowOnError
  >({
    responseTransformer: createPeriodEventPeriodPostResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get My Periods
 */
export const getMyPeriodsPeriodMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMyPeriodsPeriodMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMyPeriodsPeriodMeGetResponses,
    GetMyPeriodsPeriodMeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/me/",
    ...options,
  });

/**
 * Delete Period
 */
export const deletePeriodPeriodMePeriodIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePeriodPeriodMePeriodIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeletePeriodPeriodMePeriodIdDeleteResponses,
    DeletePeriodPeriodMePeriodIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/me/{period_id}",
    ...options,
  });

/**
 * Get Single Period
 */
export const getSinglePeriodPeriodMePeriodIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSinglePeriodPeriodMePeriodIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSinglePeriodPeriodMePeriodIdGetResponses,
    GetSinglePeriodPeriodMePeriodIdGetErrors,
    ThrowOnError
  >({
    responseTransformer: getSinglePeriodPeriodMePeriodIdGetResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/me/{period_id}",
    ...options,
  });

/**
 * Update Period
 */
export const updatePeriodPeriodMePeriodIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePeriodPeriodMePeriodIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdatePeriodPeriodMePeriodIdPatchResponses,
    UpdatePeriodPeriodMePeriodIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer: updatePeriodPeriodMePeriodIdPatchResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/me/{period_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get My Periods Csv
 */
export const getMyPeriodsCsvPeriodMeCsvGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMyPeriodsCsvPeriodMeCsvGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMyPeriodsCsvPeriodMeCsvGetResponses,
    GetMyPeriodsCsvPeriodMeCsvGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/me/csv/",
    ...options,
  });

/**
 * Get Next Period
 */
export const getNextPeriodPeriodMeNextGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetNextPeriodPeriodMeNextGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetNextPeriodPeriodMeNextGetResponses,
    GetNextPeriodPeriodMeNextGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/me/next/",
    ...options,
  });

/**
 * Get Partner Periods
 */
export const getPartnerPeriodsPeriodPartnerPartnerIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPartnerPeriodsPeriodPartnerPartnerIdGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetPartnerPeriodsPeriodPartnerPartnerIdGetResponses,
    GetPartnerPeriodsPeriodPartnerPartnerIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/partner/{partner_id}/",
    ...options,
  });

/**
 * Get Partner Periods Csv
 */
export const getPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetResponses,
    GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/period/partner/{partner_id}/csv/",
    ...options,
  });

/**
 * Get Temp Readings
 */
export const getTempReadingsTempGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTempReadingsTempGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetTempReadingsTempGetResponses,
    GetTempReadingsTempGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/",
    ...options,
  });

/**
 * Create Temp Reading
 */
export const createTempReadingTempPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTempReadingTempPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateTempReadingTempPostResponses,
    CreateTempReadingTempPostErrors,
    ThrowOnError
  >({
    responseTransformer: createTempReadingTempPostResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get My Readings
 */
export const getMyReadingsTempMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMyReadingsTempMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMyReadingsTempMeGetResponses,
    GetMyReadingsTempMeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/me/",
    ...options,
  });

/**
 * Delete Temp
 */
export const deleteTempTempMeTemperatureIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTempTempMeTemperatureIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTempTempMeTemperatureIdDeleteResponses,
    DeleteTempTempMeTemperatureIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/me/{temperature_id}",
    ...options,
  });

/**
 * Get Single Reading
 */
export const getSingleReadingTempMeTemperatureIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSingleReadingTempMeTemperatureIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSingleReadingTempMeTemperatureIdGetResponses,
    GetSingleReadingTempMeTemperatureIdGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      getSingleReadingTempMeTemperatureIdGetResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/me/{temperature_id}",
    ...options,
  });

/**
 * Update Reading
 */
export const updateReadingTempMeTemperatureIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateReadingTempMeTemperatureIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateReadingTempMeTemperatureIdPatchResponses,
    UpdateReadingTempMeTemperatureIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer:
      updateReadingTempMeTemperatureIdPatchResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/me/{temperature_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get My Temp Averages
 */
export const getMyTempAveragesTempMeAveragesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMyTempAveragesTempMeAveragesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMyTempAveragesTempMeAveragesGetResponses,
    GetMyTempAveragesTempMeAveragesGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/me/averages/",
    ...options,
  });

/**
 * Get My Temp Readings Csv
 */
export const getMyTempReadingsCsvTempMeCsvGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMyTempReadingsCsvTempMeCsvGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMyTempReadingsCsvTempMeCsvGetResponses,
    GetMyTempReadingsCsvTempMeCsvGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/me/csv/",
    ...options,
  });

/**
 * Get Partner Temperatures
 */
export const getPartnerTemperaturesTempPartnerPartnerIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPartnerTemperaturesTempPartnerPartnerIdGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetPartnerTemperaturesTempPartnerPartnerIdGetResponses,
    GetPartnerTemperaturesTempPartnerPartnerIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/partner/{partner_id}/",
    ...options,
  });

/**
 * Get Partner Temp Readings Csv
 */
export const getPartnerTempReadingsCsvTempPartnerPartnerIdCsvGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetResponses,
    GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/temp/partner/{partner_id}/csv/",
    ...options,
  });

/**
 * Get Symptom Events
 */
export const getSymptomEventsSymptomsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetSymptomEventsSymptomsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSymptomEventsSymptomsGetResponses,
    GetSymptomEventsSymptomsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/",
    ...options,
  });

/**
 * Create Symptom Event
 */
export const createSymptomEventSymptomsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSymptomEventSymptomsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSymptomEventSymptomsPostResponses,
    CreateSymptomEventSymptomsPostErrors,
    ThrowOnError
  >({
    responseTransformer: createSymptomEventSymptomsPostResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get My Symptom Events
 */
export const getMySymptomEventsSymptomsMeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMySymptomEventsSymptomsMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMySymptomEventsSymptomsMeGetResponses,
    GetMySymptomEventsSymptomsMeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/me/",
    ...options,
  });

/**
 * Delete Symptom Event
 */
export const deleteSymptomEventSymptomsMeSymptomIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteSymptomEventSymptomsMeSymptomIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteSymptomEventSymptomsMeSymptomIdDeleteResponses,
    DeleteSymptomEventSymptomsMeSymptomIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/me/{symptom_id}",
    ...options,
  });

/**
 * Get Single Symptom Event
 */
export const getSingleSymptomEventSymptomsMeSymptomIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetSingleSymptomEventSymptomsMeSymptomIdGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetSingleSymptomEventSymptomsMeSymptomIdGetResponses,
    GetSingleSymptomEventSymptomsMeSymptomIdGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      getSingleSymptomEventSymptomsMeSymptomIdGetResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/me/{symptom_id}",
    ...options,
  });

/**
 * Update Symptom Event
 */
export const updateSymptomEventSymptomsMeSymptomIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateSymptomEventSymptomsMeSymptomIdPatchData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    UpdateSymptomEventSymptomsMeSymptomIdPatchResponses,
    UpdateSymptomEventSymptomsMeSymptomIdPatchErrors,
    ThrowOnError
  >({
    responseTransformer:
      updateSymptomEventSymptomsMeSymptomIdPatchResponseTransformer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/me/{symptom_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Export Symptoms Csv
 */
export const exportSymptomsCsvSymptomsMeCsvGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ExportSymptomsCsvSymptomsMeCsvGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ExportSymptomsCsvSymptomsMeCsvGetResponses,
    ExportSymptomsCsvSymptomsMeCsvGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/me/csv/",
    ...options,
  });

/**
 * Get Partner Symptoms
 */
export const getPartnerSymptomsSymptomsPartnerPartnerIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPartnerSymptomsSymptomsPartnerPartnerIdGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponses,
    GetPartnerSymptomsSymptomsPartnerPartnerIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/partner/{partner_id}/",
    ...options,
  });

/**
 * Export Partner Symptoms Csv
 */
export const exportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetResponses,
    ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/symptoms/partner/{partner_id}/csv/",
    ...options,
  });

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: healthCheckHealthGetResponseTransformer,
    url: "/health",
    ...options,
  });
