// This file is auto-generated by @hey-api/openapi-ts

import type {
  AddPartnerUsersMePartnersPartnerIdPostResponse,
  CreatePeriodEventPeriodPostResponse,
  CreateSymptomEventSymptomsPostResponse,
  CreateTempReadingTempPostResponse,
  GetAllPeriodsPeriodGetResponse,
  GetMyEventsUsersMeEventsGetResponse,
  GetMyPartnersUsersMePartnersGetResponse,
  GetMyPeriodsPeriodMeGetResponse,
  GetMyReadingsTempMeGetResponse,
  GetMySymptomEventsSymptomsMeGetResponse,
  GetNextPeriodPeriodMeNextGetResponse,
  GetPartnerPeriodsPeriodPartnerPartnerIdGetResponse,
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponse,
  GetPartnerTemperaturesTempPartnerPartnerIdGetResponse,
  GetSinglePeriodPeriodMePeriodIdGetResponse,
  GetSingleReadingTempMeTemperatureIdGetResponse,
  GetSingleSymptomEventSymptomsMeSymptomIdGetResponse,
  GetSymptomEventsSymptomsGetResponse,
  GetTempReadingsTempGetResponse,
  GetUsersUsersGetResponse,
  HealthCheckHealthGetResponse,
  ReadMeUsersMeGetResponse,
  UpdateMeUsersMePatchResponse,
  UpdatePeriodPeriodMePeriodIdPatchResponse,
  UpdateReadingTempMeTemperatureIdPatchResponse,
  UpdateSymptomEventSymptomsMeSymptomIdPatchResponse,
} from './types.gen';

const temperatureSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

const responseSchemaResponseTransformer = (data: any) => {
  for (const key of Object.keys(data.data)) {
    data.data[key] = data.data[key].map((item: any) =>
      temperatureSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const getUsersUsersGetResponseTransformer = async (
  data: any,
): Promise<GetUsersUsersGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

const temperatureStateSchemaResponseTransformer = (data: any) => {
  if (data.last_evaluated) {
    data.last_evaluated = new Date(data.last_evaluated);
  }
  return data;
};

const cycleSchemaResponseTransformer = (data: any) => {
  if (data.last_evaluated) {
    data.last_evaluated = new Date(data.last_evaluated);
  }
  return data;
};

const userProfileSchemaResponseTransformer = (data: any) => {
  if (data.temp_state) {
    data.temp_state = temperatureStateSchemaResponseTransformer(data.temp_state);
  }
  if (data.cycle_state) {
    data.cycle_state = cycleSchemaResponseTransformer(data.cycle_state);
  }
  return data;
};

export const readMeUsersMeGetResponseTransformer = async (
  data: any,
): Promise<ReadMeUsersMeGetResponse> => {
  data = userProfileSchemaResponseTransformer(data);
  return data;
};

export const updateMeUsersMePatchResponseTransformer = async (
  data: any,
): Promise<UpdateMeUsersMePatchResponse> => {
  data = userProfileSchemaResponseTransformer(data);
  return data;
};

export const getMyEventsUsersMeEventsGetResponseTransformer = async (
  data: any,
): Promise<GetMyEventsUsersMeEventsGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const getMyPartnersUsersMePartnersGetResponseTransformer = async (
  data: any,
): Promise<GetMyPartnersUsersMePartnersGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const addPartnerUsersMePartnersPartnerIdPostResponseTransformer = async (
  data: any,
): Promise<AddPartnerUsersMePartnersPartnerIdPostResponse> => {
  data = userProfileSchemaResponseTransformer(data);
  return data;
};

export const getAllPeriodsPeriodGetResponseTransformer = async (
  data: any,
): Promise<GetAllPeriodsPeriodGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

const periodSchemaResponseTransformer = (data: any) => {
  data.start_date = new Date(data.start_date);
  if (data.end_date) {
    data.end_date = new Date(data.end_date);
  }
  return data;
};

export const createPeriodEventPeriodPostResponseTransformer = async (
  data: any,
): Promise<CreatePeriodEventPeriodPostResponse> => {
  data = periodSchemaResponseTransformer(data);
  return data;
};

export const getMyPeriodsPeriodMeGetResponseTransformer = async (
  data: any,
): Promise<GetMyPeriodsPeriodMeGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const getSinglePeriodPeriodMePeriodIdGetResponseTransformer = async (
  data: any,
): Promise<GetSinglePeriodPeriodMePeriodIdGetResponse> => {
  data = periodSchemaResponseTransformer(data);
  return data;
};

export const updatePeriodPeriodMePeriodIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdatePeriodPeriodMePeriodIdPatchResponse> => {
  data = periodSchemaResponseTransformer(data);
  return data;
};

const predictedPeriodSchemaResponseTransformer = (data: any) => {
  data.start_date = new Date(data.start_date);
  data.end_date = new Date(data.end_date);
  return data;
};

export const getNextPeriodPeriodMeNextGetResponseTransformer = async (
  data: any,
): Promise<GetNextPeriodPeriodMeNextGetResponse> => {
  if (data) {
    data = predictedPeriodSchemaResponseTransformer(data);
  }
  return data;
};

export const getPartnerPeriodsPeriodPartnerPartnerIdGetResponseTransformer = async (
  data: any,
): Promise<GetPartnerPeriodsPeriodPartnerPartnerIdGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const getTempReadingsTempGetResponseTransformer = async (
  data: any,
): Promise<GetTempReadingsTempGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const createTempReadingTempPostResponseTransformer = async (
  data: any,
): Promise<CreateTempReadingTempPostResponse> => {
  data = temperatureSchemaResponseTransformer(data);
  return data;
};

export const getMyReadingsTempMeGetResponseTransformer = async (
  data: any,
): Promise<GetMyReadingsTempMeGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const getSingleReadingTempMeTemperatureIdGetResponseTransformer = async (
  data: any,
): Promise<GetSingleReadingTempMeTemperatureIdGetResponse> => {
  data = temperatureSchemaResponseTransformer(data);
  return data;
};

export const updateReadingTempMeTemperatureIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateReadingTempMeTemperatureIdPatchResponse> => {
  data = temperatureSchemaResponseTransformer(data);
  return data;
};

export const getPartnerTemperaturesTempPartnerPartnerIdGetResponseTransformer = async (
  data: any,
): Promise<GetPartnerTemperaturesTempPartnerPartnerIdGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const getSymptomEventsSymptomsGetResponseTransformer = async (
  data: any,
): Promise<GetSymptomEventsSymptomsGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

const symptomEventSchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date);
  return data;
};

export const createSymptomEventSymptomsPostResponseTransformer = async (
  data: any,
): Promise<CreateSymptomEventSymptomsPostResponse> => {
  data = symptomEventSchemaResponseTransformer(data);
  return data;
};

export const getMySymptomEventsSymptomsMeGetResponseTransformer = async (
  data: any,
): Promise<GetMySymptomEventsSymptomsMeGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const getSingleSymptomEventSymptomsMeSymptomIdGetResponseTransformer = async (
  data: any,
): Promise<GetSingleSymptomEventSymptomsMeSymptomIdGetResponse> => {
  data = symptomEventSchemaResponseTransformer(data);
  return data;
};

export const updateSymptomEventSymptomsMeSymptomIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateSymptomEventSymptomsMeSymptomIdPatchResponse> => {
  data = symptomEventSchemaResponseTransformer(data);
  return data;
};

export const getPartnerSymptomsSymptomsPartnerPartnerIdGetResponseTransformer = async (
  data: any,
): Promise<GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

const healthCheckSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

export const healthCheckHealthGetResponseTransformer = async (
  data: any,
): Promise<HealthCheckHealthGetResponse> => {
  data = healthCheckSchemaResponseTransformer(data);
  return data;
};
