// This file is auto-generated by @hey-api/openapi-ts

import type {
  AddPartnerUsersMePartnersPartnerIdPostResponse,
  CreatePeriodEventPeriodPostResponse,
  CreateSymptomEventSymptomsPostResponse,
  CreateTempReadingTempPostResponse,
  GetSinglePeriodPeriodMePeriodIdGetResponse,
  GetSingleReadingTempMeTemperatureIdGetResponse,
  GetSingleSymptomEventSymptomsMeSymptomIdGetResponse,
  HealthCheckHealthGetResponse,
  ReadMeUsersMeGetResponse,
  UpdateMeUsersMePatchResponse,
  UpdatePeriodPeriodMePeriodIdPatchResponse,
  UpdateReadingTempMeTemperatureIdPatchResponse,
  UpdateSymptomEventSymptomsMeSymptomIdPatchResponse,
} from "./types.gen";

const temperatureStateSchemaResponseTransformer = (data: any) => {
  if (data.last_evaluated) {
    data.last_evaluated = new Date(data.last_evaluated);
  }
  return data;
};

const cycleSchemaResponseTransformer = (data: any) => {
  if (data.last_period_start) {
    data.last_period_start = new Date(data.last_period_start);
  }
  if (data.last_evaluated) {
    data.last_evaluated = new Date(data.last_evaluated);
  }
  return data;
};

const userProfileSchemaResponseTransformer = (data: any) => {
  if (data.temp_state) {
    data.temp_state = temperatureStateSchemaResponseTransformer(
      data.temp_state,
    );
  }
  if (data.cycle_state) {
    data.cycle_state = cycleSchemaResponseTransformer(data.cycle_state);
  }
  return data;
};

export const readMeUsersMeGetResponseTransformer = async (
  data: any,
): Promise<ReadMeUsersMeGetResponse> => {
  data = userProfileSchemaResponseTransformer(data);
  return data;
};

export const updateMeUsersMePatchResponseTransformer = async (
  data: any,
): Promise<UpdateMeUsersMePatchResponse> => {
  data = userProfileSchemaResponseTransformer(data);
  return data;
};

export const addPartnerUsersMePartnersPartnerIdPostResponseTransformer = async (
  data: any,
): Promise<AddPartnerUsersMePartnersPartnerIdPostResponse> => {
  data = userProfileSchemaResponseTransformer(data);
  return data;
};

const periodSchemaResponseTransformer = (data: any) => {
  data.start_date = new Date(data.start_date);
  if (data.end_date) {
    data.end_date = new Date(data.end_date);
  }
  return data;
};

export const createPeriodEventPeriodPostResponseTransformer = async (
  data: any,
): Promise<CreatePeriodEventPeriodPostResponse> => {
  data = periodSchemaResponseTransformer(data);
  return data;
};

export const getSinglePeriodPeriodMePeriodIdGetResponseTransformer = async (
  data: any,
): Promise<GetSinglePeriodPeriodMePeriodIdGetResponse> => {
  data = periodSchemaResponseTransformer(data);
  return data;
};

export const updatePeriodPeriodMePeriodIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdatePeriodPeriodMePeriodIdPatchResponse> => {
  data = periodSchemaResponseTransformer(data);
  return data;
};

const temperatureSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

export const createTempReadingTempPostResponseTransformer = async (
  data: any,
): Promise<CreateTempReadingTempPostResponse> => {
  data = temperatureSchemaResponseTransformer(data);
  return data;
};

export const getSingleReadingTempMeTemperatureIdGetResponseTransformer = async (
  data: any,
): Promise<GetSingleReadingTempMeTemperatureIdGetResponse> => {
  data = temperatureSchemaResponseTransformer(data);
  return data;
};

export const updateReadingTempMeTemperatureIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateReadingTempMeTemperatureIdPatchResponse> => {
  data = temperatureSchemaResponseTransformer(data);
  return data;
};

const symptomEventSchemaResponseTransformer = (data: any) => {
  data.date = new Date(data.date);
  return data;
};

export const createSymptomEventSymptomsPostResponseTransformer = async (
  data: any,
): Promise<CreateSymptomEventSymptomsPostResponse> => {
  data = symptomEventSchemaResponseTransformer(data);
  return data;
};

export const getSingleSymptomEventSymptomsMeSymptomIdGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetSingleSymptomEventSymptomsMeSymptomIdGetResponse> => {
    data = symptomEventSchemaResponseTransformer(data);
    return data;
  };

export const updateSymptomEventSymptomsMeSymptomIdPatchResponseTransformer =
  async (
    data: any,
  ): Promise<UpdateSymptomEventSymptomsMeSymptomIdPatchResponse> => {
    data = symptomEventSchemaResponseTransformer(data);
    return data;
  };

const healthCheckSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

export const healthCheckHealthGetResponseTransformer = async (
  data: any,
): Promise<HealthCheckHealthGetResponse> => {
  data = healthCheckSchemaResponseTransformer(data);
  return data;
};
