// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccessToken
 */
export type AccessToken = {
  /**
   * Token Type
   */
  token_type: string;
  /**
   * Access Token
   */
  access_token: string;
};

/**
 * ApplicationInfo
 */
export type ApplicationInfo = {
  /**
   * App Name
   */
  app_name: string;
  /**
   * Version
   */
  version: string;
};

/**
 * Body_login_auth__post
 */
export type BodyLoginAuthPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * CreatePeriodParams
 */
export type CreatePeriodParams = {
  /**
   * Start Date
   *
   * Start date
   */
  start_date?: string;
  /**
   * End Date
   *
   * End date (Optional)
   */
  end_date?: string | null;
};

/**
 * CreateSymptomParams
 */
export type CreateSymptomParams = {
  /**
   * Date
   *
   * Date of the symptom event
   */
  date?: string | null;
  flow_intensity?: FlowIntensity | null;
  /**
   * Symptoms
   */
  symptoms?: Array<string> | null;
  /**
   * Mood
   */
  mood?: Array<string> | null;
  /**
   * Ovulation Test
   */
  ovulation_test?: boolean | null;
  /**
   * Discharge
   */
  discharge?: Array<string> | null;
  /**
   * Sex
   */
  sex?: Array<string> | null;
};

/**
 * CreateTempParams
 */
export type CreateTempParams = {
  /**
   * Temperature
   */
  temperature: number;
};

/**
 * Cycle
 */
export type Cycle = {
  /**
   * Pid
   */
  pid?: number | null;
  /**
   * User Id
   */
  user_id: string;
  state?: CycleState;
  /**
   * Avg Cycle Length
   */
  avg_cycle_length?: number | null;
  /**
   * Avg Period Length
   */
  avg_period_length?: number | null;
  /**
   * Last Period Start
   */
  last_period_start?: Date | null;
  /**
   * Last Evaluated
   */
  last_evaluated?: Date | null;
};

/**
 * CycleState
 */
export const CycleState = {
  LEARNING: "learning",
  STABLE: "stable",
  UNSTABLE: "unstable",
} as const;

/**
 * CycleState
 */
export type CycleState = (typeof CycleState)[keyof typeof CycleState];

/**
 * FlowIntensity
 */
export const FlowIntensity = {
  0: "0",
  1: "1",
  2: "2",
  3: "3",
  4: "4",
} as const;

/**
 * FlowIntensity
 */
export type FlowIntensity = (typeof FlowIntensity)[keyof typeof FlowIntensity];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 */
export type HealthCheck = {
  /**
   * Status
   */
  status: string;
  /**
   * Timestamp
   */
  timestamp: Date;
};

/**
 * Period
 *
 * Period Event model.
 *
 * This is the class representing the Period table in the database.
 *
 * - user_id
 * - start_date, assume TZ-naive on read due to SQLite limitations
 * - end_date, assume TZ-naive on read due to SQLite limitations
 * - duration
 */
export type Period = {
  /**
   * User Id
   */
  user_id: string;
  /**
   * Start Date
   */
  start_date: Date;
  /**
   * End Date
   */
  end_date?: Date | null;
  /**
   * Duration
   */
  duration?: number | null;
  /**
   * Pid
   */
  pid?: number;
  /**
   * Luteal Length
   */
  luteal_length?: number | null;
};

/**
 * PeriodUpdate
 */
export type PeriodUpdate = {
  /**
   * Start Date
   *
   * YYYY-MM-DD format
   */
  start_date?: string | null;
  /**
   * End Date
   *
   * YYYY-MM-DD format
   */
  end_date?: string | null;
};

/**
 * PredictedPeriod
 */
export type PredictedPeriod = {
  /**
   * Start Date
   */
  start_date: Date;
  /**
   * End Date
   */
  end_date: Date;
  /**
   * Confidence
   */
  confidence?: number | null;
};

/**
 * ResourceDeleteResponse
 */
export type ResourceDeleteResponse = {
  /**
   * Resource Type
   */
  resource_type: string;
  /**
   * Resource Id
   */
  resource_id: string;
};

/**
 * Response
 *
 * Base response model with count field used for list endpoints.
 */
export type Response = {
  /**
   * Count
   */
  count: number;
  /**
   * Data
   */
  data: {
    [key: string]: Array<Temperature | Period | SymptomEvent | UserSafe>;
  };
};

/**
 * SymptomEvent
 *
 * Symptom Event model.
 *
 * This is the class representing the Symptom Event table in the database.
 * - user_id
 * - date
 * - flow_intensity
 * - symptoms
 * - mood
 * - ovulation_test
 * - discharge
 * - sex
 */
export type SymptomEvent = {
  /**
   * User Id
   */
  user_id: string;
  /**
   * Date
   */
  date: Date;
  flow_intensity: FlowIntensity | null;
  /**
   * Symptoms
   */
  symptoms: Array<string> | null;
  /**
   * Mood
   */
  mood: Array<string> | null;
  /**
   * Ovulation Test
   */
  ovulation_test?: boolean | null;
  /**
   * Discharge
   */
  discharge: Array<string> | null;
  /**
   * Sex
   */
  sex: Array<string> | null;
  /**
   * Pid
   */
  pid?: number;
};

/**
 * TempPhase
 */
export const TempPhase = {
  LEARNING: "learning",
  LOW_PHASE: "low_phase",
  ELEVATED_PHASE: "elevated_phase",
  UNKNOWN: "unknown",
} as const;

/**
 * TempPhase
 */
export type TempPhase = (typeof TempPhase)[keyof typeof TempPhase];

/**
 * TempUpdate
 */
export type TempUpdate = {
  /**
   * Temperature
   */
  temperature?: number | null;
  /**
   * Timestamp
   *
   * YYYY-MM-DD format
   */
  timestamp?: string | null;
};

/**
 * Temperature
 *
 * Temperature Event model.
 *
 * This is the class representing the Temperature table in the database.
 *
 * - user_id
 * - temperature
 * - pid
 * - timestamp, assume TZ-naive on read due to SQLite limitations
 */
export type Temperature = {
  /**
   * Temperature
   */
  temperature: number;
  /**
   * User Id
   */
  user_id: string;
  /**
   * Timestamp
   */
  timestamp: Date;
  /**
   * Pid
   */
  pid?: number | null;
};

/**
 * TemperatureEMA
 */
export type TemperatureEma = {
  /**
   * Timestamp
   */
  timestamp: string;
  /**
   * Temperature
   */
  temperature: number;
  /**
   * Ewm
   */
  ewm: number;
  /**
   * Baseline
   */
  baseline: number;
};

/**
 * TemperatureState
 */
export type TemperatureState = {
  /**
   * Pid
   */
  pid?: number | null;
  /**
   * User Id
   */
  user_id: string;
  phase?: TempPhase;
  /**
   * Baseline
   */
  baseline?: number | null;
  /**
   * Last Evaluated
   */
  last_evaluated?: Date | null;
};

/**
 * UpdateSymptomEvent
 */
export type UpdateSymptomEvent = {
  /**
   * Date
   *
   * YYYY-MM-DD format
   */
  date?: string | null;
  flow_intensity?: FlowIntensity | null;
  /**
   * Symptoms
   */
  symptoms?: Array<string> | null;
  /**
   * Mood
   */
  mood?: Array<string> | null;
  /**
   * Ovulation Test
   */
  ovulation_test?: boolean | null;
  /**
   * Discharge
   */
  discharge?: Array<string> | null;
  /**
   * Sex
   */
  sex?: Array<string> | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Is Disabled
   */
  is_disabled?: boolean;
  /**
   * Is Admin
   */
  is_admin?: boolean;
  /**
   * Username
   */
  username: string;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * UserProfile
 *
 * Everything but the hashed password.
 * - user_id
 * - username
 * - display_name
 * - is_disabled
 * - is_admin
 * - partners
 */
export type UserProfile = {
  /**
   * Is Disabled
   */
  is_disabled?: boolean;
  /**
   * Is Admin
   */
  is_admin?: boolean;
  /**
   * Username
   */
  username: string;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * User Id
   */
  user_id?: string;
  temp_state?: TemperatureState | null;
  cycle_state?: Cycle | null;
  /**
   * Partners
   */
  partners?: Array<UserSafe> | null;
};

/**
 * UserSafe
 *
 * Everything but the hashed password and period stats.
 * - user_id
 * - username
 * - display_name
 * - is_disabled
 * - is_admin
 */
export type UserSafe = {
  /**
   * Is Disabled
   */
  is_disabled?: boolean;
  /**
   * Is Admin
   */
  is_admin?: boolean;
  /**
   * Username
   */
  username: string;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * User Id
   */
  user_id?: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Password
   */
  password?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type LoginAuthPostData = {
  body: BodyLoginAuthPost;
  path?: never;
  query?: never;
  url: "/auth/";
};

export type LoginAuthPostErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginAuthPostError = LoginAuthPostErrors[keyof LoginAuthPostErrors];

export type LoginAuthPostResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type LoginAuthPostResponse =
  LoginAuthPostResponses[keyof LoginAuthPostResponses];

export type RefreshTokensAuthRefreshPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/refresh";
};

export type RefreshTokensAuthRefreshPostErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type RefreshTokensAuthRefreshPostResponses = {
  /**
   * Successful Response
   */
  200: AccessToken;
};

export type RefreshTokensAuthRefreshPostResponse =
  RefreshTokensAuthRefreshPostResponses[keyof RefreshTokensAuthRefreshPostResponses];

export type GetUsersUsersGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/users/";
};

export type GetUsersUsersGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUsersUsersGetError =
  GetUsersUsersGetErrors[keyof GetUsersUsersGetErrors];

export type GetUsersUsersGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetUsersUsersGetResponse =
  GetUsersUsersGetResponses[keyof GetUsersUsersGetResponses];

export type CreateUserUsersPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/users/";
};

export type CreateUserUsersPostErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserUsersPostError =
  CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
  /**
   * Successful Response
   */
  200: UserSafe;
};

export type CreateUserUsersPostResponse =
  CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type DeleteMeUsersMeDeleteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me/";
};

export type DeleteMeUsersMeDeleteErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type DeleteMeUsersMeDeleteResponses = {
  /**
   * Successful Response
   */
  200: ResourceDeleteResponse;
};

export type DeleteMeUsersMeDeleteResponse =
  DeleteMeUsersMeDeleteResponses[keyof DeleteMeUsersMeDeleteResponses];

export type ReadMeUsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me/";
};

export type ReadMeUsersMeGetErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type ReadMeUsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserProfile;
};

export type ReadMeUsersMeGetResponse =
  ReadMeUsersMeGetResponses[keyof ReadMeUsersMeGetResponses];

export type UpdateMeUsersMePatchData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/users/me/";
};

export type UpdateMeUsersMePatchErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateMeUsersMePatchError =
  UpdateMeUsersMePatchErrors[keyof UpdateMeUsersMePatchErrors];

export type UpdateMeUsersMePatchResponses = {
  /**
   * Successful Response
   */
  200: UserProfile;
};

export type UpdateMeUsersMePatchResponse =
  UpdateMeUsersMePatchResponses[keyof UpdateMeUsersMePatchResponses];

export type GetMyEventsUsersMeEventsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/users/me/events/";
};

export type GetMyEventsUsersMeEventsGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyEventsUsersMeEventsGetError =
  GetMyEventsUsersMeEventsGetErrors[keyof GetMyEventsUsersMeEventsGetErrors];

export type GetMyEventsUsersMeEventsGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetMyEventsUsersMeEventsGetResponse =
  GetMyEventsUsersMeEventsGetResponses[keyof GetMyEventsUsersMeEventsGetResponses];

export type GetMyEventsCsvUsersMeEventsCsvGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/users/me/events/csv/";
};

export type GetMyEventsCsvUsersMeEventsCsvGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyEventsCsvUsersMeEventsCsvGetError =
  GetMyEventsCsvUsersMeEventsCsvGetErrors[keyof GetMyEventsCsvUsersMeEventsCsvGetErrors];

export type GetMyEventsCsvUsersMeEventsCsvGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetMyPartnersUsersMePartnersGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me/partners/";
};

export type GetMyPartnersUsersMePartnersGetErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetMyPartnersUsersMePartnersGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetMyPartnersUsersMePartnersGetResponse =
  GetMyPartnersUsersMePartnersGetResponses[keyof GetMyPartnersUsersMePartnersGetResponses];

export type RemovePartnerUsersMePartnersPartnerIdDeleteData = {
  body?: never;
  path: {
    /**
     * Partner Id
     */
    partner_id: string;
  };
  query?: never;
  url: "/users/me/partners/{partner_id}/";
};

export type RemovePartnerUsersMePartnersPartnerIdDeleteErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemovePartnerUsersMePartnersPartnerIdDeleteError =
  RemovePartnerUsersMePartnersPartnerIdDeleteErrors[keyof RemovePartnerUsersMePartnersPartnerIdDeleteErrors];

export type RemovePartnerUsersMePartnersPartnerIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ResourceDeleteResponse;
};

export type RemovePartnerUsersMePartnersPartnerIdDeleteResponse =
  RemovePartnerUsersMePartnersPartnerIdDeleteResponses[keyof RemovePartnerUsersMePartnersPartnerIdDeleteResponses];

export type AddPartnerUsersMePartnersPartnerIdPostData = {
  body?: never;
  path: {
    /**
     * Partner Id
     */
    partner_id: string;
  };
  query?: never;
  url: "/users/me/partners/{partner_id}/";
};

export type AddPartnerUsersMePartnersPartnerIdPostErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddPartnerUsersMePartnersPartnerIdPostError =
  AddPartnerUsersMePartnersPartnerIdPostErrors[keyof AddPartnerUsersMePartnersPartnerIdPostErrors];

export type AddPartnerUsersMePartnersPartnerIdPostResponses = {
  /**
   * Successful Response
   */
  200: UserProfile;
};

export type AddPartnerUsersMePartnersPartnerIdPostResponse =
  AddPartnerUsersMePartnersPartnerIdPostResponses[keyof AddPartnerUsersMePartnersPartnerIdPostResponses];

export type GetAllPeriodsPeriodGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/period/";
};

export type GetAllPeriodsPeriodGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAllPeriodsPeriodGetError =
  GetAllPeriodsPeriodGetErrors[keyof GetAllPeriodsPeriodGetErrors];

export type GetAllPeriodsPeriodGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetAllPeriodsPeriodGetResponse =
  GetAllPeriodsPeriodGetResponses[keyof GetAllPeriodsPeriodGetResponses];

export type CreatePeriodEventPeriodPostData = {
  body: CreatePeriodParams;
  path?: never;
  query?: never;
  url: "/period/";
};

export type CreatePeriodEventPeriodPostErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePeriodEventPeriodPostError =
  CreatePeriodEventPeriodPostErrors[keyof CreatePeriodEventPeriodPostErrors];

export type CreatePeriodEventPeriodPostResponses = {
  /**
   * Successful Response
   */
  200: Period;
};

export type CreatePeriodEventPeriodPostResponse =
  CreatePeriodEventPeriodPostResponses[keyof CreatePeriodEventPeriodPostResponses];

export type GetMyPeriodsPeriodMeGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/period/me/";
};

export type GetMyPeriodsPeriodMeGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyPeriodsPeriodMeGetError =
  GetMyPeriodsPeriodMeGetErrors[keyof GetMyPeriodsPeriodMeGetErrors];

export type GetMyPeriodsPeriodMeGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetMyPeriodsPeriodMeGetResponse =
  GetMyPeriodsPeriodMeGetResponses[keyof GetMyPeriodsPeriodMeGetResponses];

export type DeletePeriodPeriodMePeriodIdDeleteData = {
  body?: never;
  path: {
    /**
     * Period Id
     */
    period_id: number;
  };
  query?: never;
  url: "/period/me/{period_id}";
};

export type DeletePeriodPeriodMePeriodIdDeleteErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePeriodPeriodMePeriodIdDeleteError =
  DeletePeriodPeriodMePeriodIdDeleteErrors[keyof DeletePeriodPeriodMePeriodIdDeleteErrors];

export type DeletePeriodPeriodMePeriodIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ResourceDeleteResponse;
};

export type DeletePeriodPeriodMePeriodIdDeleteResponse =
  DeletePeriodPeriodMePeriodIdDeleteResponses[keyof DeletePeriodPeriodMePeriodIdDeleteResponses];

export type GetSinglePeriodPeriodMePeriodIdGetData = {
  body?: never;
  path: {
    /**
     * Period Id
     */
    period_id: number;
  };
  query?: never;
  url: "/period/me/{period_id}";
};

export type GetSinglePeriodPeriodMePeriodIdGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSinglePeriodPeriodMePeriodIdGetError =
  GetSinglePeriodPeriodMePeriodIdGetErrors[keyof GetSinglePeriodPeriodMePeriodIdGetErrors];

export type GetSinglePeriodPeriodMePeriodIdGetResponses = {
  /**
   * Successful Response
   */
  200: Period;
};

export type GetSinglePeriodPeriodMePeriodIdGetResponse =
  GetSinglePeriodPeriodMePeriodIdGetResponses[keyof GetSinglePeriodPeriodMePeriodIdGetResponses];

export type UpdatePeriodPeriodMePeriodIdPatchData = {
  body: PeriodUpdate;
  path: {
    /**
     * Period Id
     */
    period_id: number;
  };
  query?: never;
  url: "/period/me/{period_id}";
};

export type UpdatePeriodPeriodMePeriodIdPatchErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePeriodPeriodMePeriodIdPatchError =
  UpdatePeriodPeriodMePeriodIdPatchErrors[keyof UpdatePeriodPeriodMePeriodIdPatchErrors];

export type UpdatePeriodPeriodMePeriodIdPatchResponses = {
  /**
   * Successful Response
   */
  200: Period;
};

export type UpdatePeriodPeriodMePeriodIdPatchResponse =
  UpdatePeriodPeriodMePeriodIdPatchResponses[keyof UpdatePeriodPeriodMePeriodIdPatchResponses];

export type GetMyPeriodsCsvPeriodMeCsvGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/period/me/csv/";
};

export type GetMyPeriodsCsvPeriodMeCsvGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyPeriodsCsvPeriodMeCsvGetError =
  GetMyPeriodsCsvPeriodMeCsvGetErrors[keyof GetMyPeriodsCsvPeriodMeCsvGetErrors];

export type GetMyPeriodsCsvPeriodMeCsvGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetNextPeriodPeriodMeNextGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/period/me/next/";
};

export type GetNextPeriodPeriodMeNextGetErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetNextPeriodPeriodMeNextGetResponses = {
  /**
   * Response Get Next Period Period Me Next  Get
   *
   * Successful Response
   */
  200: PredictedPeriod | null;
};

export type GetNextPeriodPeriodMeNextGetResponse =
  GetNextPeriodPeriodMeNextGetResponses[keyof GetNextPeriodPeriodMeNextGetResponses];

export type GetPartnerPeriodsPeriodPartnerPartnerIdGetData = {
  body?: never;
  path: {
    /**
     * Partner Id
     */
    partner_id: string;
  };
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/period/partner/{partner_id}/";
};

export type GetPartnerPeriodsPeriodPartnerPartnerIdGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPartnerPeriodsPeriodPartnerPartnerIdGetError =
  GetPartnerPeriodsPeriodPartnerPartnerIdGetErrors[keyof GetPartnerPeriodsPeriodPartnerPartnerIdGetErrors];

export type GetPartnerPeriodsPeriodPartnerPartnerIdGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetPartnerPeriodsPeriodPartnerPartnerIdGetResponse =
  GetPartnerPeriodsPeriodPartnerPartnerIdGetResponses[keyof GetPartnerPeriodsPeriodPartnerPartnerIdGetResponses];

export type GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetData = {
  body?: never;
  path: {
    /**
     * Partner Id
     */
    partner_id: string;
  };
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/period/partner/{partner_id}/csv/";
};

export type GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetError =
  GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetErrors[keyof GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetErrors];

export type GetPartnerPeriodsCsvPeriodPartnerPartnerIdCsvGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetTempReadingsTempGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/temp/";
};

export type GetTempReadingsTempGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTempReadingsTempGetError =
  GetTempReadingsTempGetErrors[keyof GetTempReadingsTempGetErrors];

export type GetTempReadingsTempGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetTempReadingsTempGetResponse =
  GetTempReadingsTempGetResponses[keyof GetTempReadingsTempGetResponses];

export type CreateTempReadingTempPostData = {
  body: CreateTempParams;
  path?: never;
  query?: never;
  url: "/temp/";
};

export type CreateTempReadingTempPostErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTempReadingTempPostError =
  CreateTempReadingTempPostErrors[keyof CreateTempReadingTempPostErrors];

export type CreateTempReadingTempPostResponses = {
  /**
   * Successful Response
   */
  200: Temperature;
};

export type CreateTempReadingTempPostResponse =
  CreateTempReadingTempPostResponses[keyof CreateTempReadingTempPostResponses];

export type GetMyReadingsTempMeGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/temp/me/";
};

export type GetMyReadingsTempMeGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyReadingsTempMeGetError =
  GetMyReadingsTempMeGetErrors[keyof GetMyReadingsTempMeGetErrors];

export type GetMyReadingsTempMeGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetMyReadingsTempMeGetResponse =
  GetMyReadingsTempMeGetResponses[keyof GetMyReadingsTempMeGetResponses];

export type DeleteTempTempMeTemperatureIdDeleteData = {
  body?: never;
  path: {
    /**
     * Temperature Id
     */
    temperature_id: number;
  };
  query?: never;
  url: "/temp/me/{temperature_id}";
};

export type DeleteTempTempMeTemperatureIdDeleteErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTempTempMeTemperatureIdDeleteError =
  DeleteTempTempMeTemperatureIdDeleteErrors[keyof DeleteTempTempMeTemperatureIdDeleteErrors];

export type DeleteTempTempMeTemperatureIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ResourceDeleteResponse;
};

export type DeleteTempTempMeTemperatureIdDeleteResponse =
  DeleteTempTempMeTemperatureIdDeleteResponses[keyof DeleteTempTempMeTemperatureIdDeleteResponses];

export type GetSingleReadingTempMeTemperatureIdGetData = {
  body?: never;
  path: {
    /**
     * Temperature Id
     */
    temperature_id: number;
  };
  query?: never;
  url: "/temp/me/{temperature_id}";
};

export type GetSingleReadingTempMeTemperatureIdGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSingleReadingTempMeTemperatureIdGetError =
  GetSingleReadingTempMeTemperatureIdGetErrors[keyof GetSingleReadingTempMeTemperatureIdGetErrors];

export type GetSingleReadingTempMeTemperatureIdGetResponses = {
  /**
   * Successful Response
   */
  200: Temperature;
};

export type GetSingleReadingTempMeTemperatureIdGetResponse =
  GetSingleReadingTempMeTemperatureIdGetResponses[keyof GetSingleReadingTempMeTemperatureIdGetResponses];

export type UpdateReadingTempMeTemperatureIdPatchData = {
  body: TempUpdate;
  path: {
    /**
     * Temperature Id
     */
    temperature_id: number;
  };
  query?: never;
  url: "/temp/me/{temperature_id}";
};

export type UpdateReadingTempMeTemperatureIdPatchErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateReadingTempMeTemperatureIdPatchError =
  UpdateReadingTempMeTemperatureIdPatchErrors[keyof UpdateReadingTempMeTemperatureIdPatchErrors];

export type UpdateReadingTempMeTemperatureIdPatchResponses = {
  /**
   * Successful Response
   */
  200: Temperature;
};

export type UpdateReadingTempMeTemperatureIdPatchResponse =
  UpdateReadingTempMeTemperatureIdPatchResponses[keyof UpdateReadingTempMeTemperatureIdPatchResponses];

export type GetMyTempAveragesTempMeAveragesGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Precision
     *
     * Decimal precision
     */
    precision?: number;
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/temp/me/averages/";
};

export type GetMyTempAveragesTempMeAveragesGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyTempAveragesTempMeAveragesGetError =
  GetMyTempAveragesTempMeAveragesGetErrors[keyof GetMyTempAveragesTempMeAveragesGetErrors];

export type GetMyTempAveragesTempMeAveragesGetResponses = {
  /**
   * Response Get My Temp Averages Temp Me Averages  Get
   *
   * Successful Response
   */
  200: Array<TemperatureEma>;
};

export type GetMyTempAveragesTempMeAveragesGetResponse =
  GetMyTempAveragesTempMeAveragesGetResponses[keyof GetMyTempAveragesTempMeAveragesGetResponses];

export type GetMyTempReadingsCsvTempMeCsvGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Precision
     *
     * Decimal precision
     */
    precision?: number;
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/temp/me/csv/";
};

export type GetMyTempReadingsCsvTempMeCsvGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMyTempReadingsCsvTempMeCsvGetError =
  GetMyTempReadingsCsvTempMeCsvGetErrors[keyof GetMyTempReadingsCsvTempMeCsvGetErrors];

export type GetMyTempReadingsCsvTempMeCsvGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetPartnerTemperaturesTempPartnerPartnerIdGetData = {
  body?: never;
  path: {
    /**
     * Partner Id
     */
    partner_id: string;
  };
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/temp/partner/{partner_id}/";
};

export type GetPartnerTemperaturesTempPartnerPartnerIdGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPartnerTemperaturesTempPartnerPartnerIdGetError =
  GetPartnerTemperaturesTempPartnerPartnerIdGetErrors[keyof GetPartnerTemperaturesTempPartnerPartnerIdGetErrors];

export type GetPartnerTemperaturesTempPartnerPartnerIdGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetPartnerTemperaturesTempPartnerPartnerIdGetResponse =
  GetPartnerTemperaturesTempPartnerPartnerIdGetResponses[keyof GetPartnerTemperaturesTempPartnerPartnerIdGetResponses];

export type GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetData = {
  body?: never;
  path: {
    /**
     * Partner Id
     */
    partner_id: string;
  };
  query?: {
    /**
     * Precision
     *
     * Decimal precision
     */
    precision?: number;
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/temp/partner/{partner_id}/csv/";
};

export type GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetError =
  GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetErrors[keyof GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetErrors];

export type GetPartnerTempReadingsCsvTempPartnerPartnerIdCsvGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetSymptomEventsSymptomsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/symptoms/";
};

export type GetSymptomEventsSymptomsGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSymptomEventsSymptomsGetError =
  GetSymptomEventsSymptomsGetErrors[keyof GetSymptomEventsSymptomsGetErrors];

export type GetSymptomEventsSymptomsGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetSymptomEventsSymptomsGetResponse =
  GetSymptomEventsSymptomsGetResponses[keyof GetSymptomEventsSymptomsGetResponses];

export type CreateSymptomEventSymptomsPostData = {
  body: CreateSymptomParams;
  path?: never;
  query?: never;
  url: "/symptoms/";
};

export type CreateSymptomEventSymptomsPostErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateSymptomEventSymptomsPostError =
  CreateSymptomEventSymptomsPostErrors[keyof CreateSymptomEventSymptomsPostErrors];

export type CreateSymptomEventSymptomsPostResponses = {
  /**
   * Successful Response
   */
  200: SymptomEvent;
};

export type CreateSymptomEventSymptomsPostResponse =
  CreateSymptomEventSymptomsPostResponses[keyof CreateSymptomEventSymptomsPostResponses];

export type GetMySymptomEventsSymptomsMeGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/symptoms/me/";
};

export type GetMySymptomEventsSymptomsMeGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMySymptomEventsSymptomsMeGetError =
  GetMySymptomEventsSymptomsMeGetErrors[keyof GetMySymptomEventsSymptomsMeGetErrors];

export type GetMySymptomEventsSymptomsMeGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetMySymptomEventsSymptomsMeGetResponse =
  GetMySymptomEventsSymptomsMeGetResponses[keyof GetMySymptomEventsSymptomsMeGetResponses];

export type DeleteSymptomEventSymptomsMeSymptomIdDeleteData = {
  body?: never;
  path: {
    /**
     * Symptom Id
     */
    symptom_id: number;
  };
  query?: never;
  url: "/symptoms/me/{symptom_id}";
};

export type DeleteSymptomEventSymptomsMeSymptomIdDeleteErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteSymptomEventSymptomsMeSymptomIdDeleteError =
  DeleteSymptomEventSymptomsMeSymptomIdDeleteErrors[keyof DeleteSymptomEventSymptomsMeSymptomIdDeleteErrors];

export type DeleteSymptomEventSymptomsMeSymptomIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: ResourceDeleteResponse;
};

export type DeleteSymptomEventSymptomsMeSymptomIdDeleteResponse =
  DeleteSymptomEventSymptomsMeSymptomIdDeleteResponses[keyof DeleteSymptomEventSymptomsMeSymptomIdDeleteResponses];

export type GetSingleSymptomEventSymptomsMeSymptomIdGetData = {
  body?: never;
  path: {
    /**
     * Symptom Id
     */
    symptom_id: number;
  };
  query?: never;
  url: "/symptoms/me/{symptom_id}";
};

export type GetSingleSymptomEventSymptomsMeSymptomIdGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSingleSymptomEventSymptomsMeSymptomIdGetError =
  GetSingleSymptomEventSymptomsMeSymptomIdGetErrors[keyof GetSingleSymptomEventSymptomsMeSymptomIdGetErrors];

export type GetSingleSymptomEventSymptomsMeSymptomIdGetResponses = {
  /**
   * Successful Response
   */
  200: SymptomEvent;
};

export type GetSingleSymptomEventSymptomsMeSymptomIdGetResponse =
  GetSingleSymptomEventSymptomsMeSymptomIdGetResponses[keyof GetSingleSymptomEventSymptomsMeSymptomIdGetResponses];

export type UpdateSymptomEventSymptomsMeSymptomIdPatchData = {
  body: UpdateSymptomEvent;
  path: {
    /**
     * Symptom Id
     */
    symptom_id: number;
  };
  query?: never;
  url: "/symptoms/me/{symptom_id}";
};

export type UpdateSymptomEventSymptomsMeSymptomIdPatchErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateSymptomEventSymptomsMeSymptomIdPatchError =
  UpdateSymptomEventSymptomsMeSymptomIdPatchErrors[keyof UpdateSymptomEventSymptomsMeSymptomIdPatchErrors];

export type UpdateSymptomEventSymptomsMeSymptomIdPatchResponses = {
  /**
   * Successful Response
   */
  200: SymptomEvent;
};

export type UpdateSymptomEventSymptomsMeSymptomIdPatchResponse =
  UpdateSymptomEventSymptomsMeSymptomIdPatchResponses[keyof UpdateSymptomEventSymptomsMeSymptomIdPatchResponses];

export type ExportSymptomsCsvSymptomsMeCsvGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/symptoms/me/csv/";
};

export type ExportSymptomsCsvSymptomsMeCsvGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ExportSymptomsCsvSymptomsMeCsvGetError =
  ExportSymptomsCsvSymptomsMeCsvGetErrors[keyof ExportSymptomsCsvSymptomsMeCsvGetErrors];

export type ExportSymptomsCsvSymptomsMeCsvGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetPartnerSymptomsSymptomsPartnerPartnerIdGetData = {
  body?: never;
  path: {
    /**
     * Partner Id
     */
    partner_id: string;
  };
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/symptoms/partner/{partner_id}/";
};

export type GetPartnerSymptomsSymptomsPartnerPartnerIdGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPartnerSymptomsSymptomsPartnerPartnerIdGetError =
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetErrors[keyof GetPartnerSymptomsSymptomsPartnerPartnerIdGetErrors];

export type GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponses = {
  /**
   * Successful Response
   */
  200: Response;
};

export type GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponse =
  GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponses[keyof GetPartnerSymptomsSymptomsPartnerPartnerIdGetResponses];

export type ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetData = {
  body?: never;
  path: {
    /**
     * Partner Id
     */
    partner_id: string;
  };
  query?: {
    /**
     * Start Date
     *
     * Start date filter
     */
    start_date?: string | null;
    /**
     * End Date
     *
     * End date filter
     */
    end_date?: string | null;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/symptoms/partner/{partner_id}/csv/";
};

export type ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetError =
  ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetErrors[keyof ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetErrors];

export type ExportPartnerSymptomsCsvSymptomsPartnerPartnerIdCsvGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: ApplicationInfo;
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthCheck;
};

export type HealthCheckHealthGetResponse =
  HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];
