"""empty message.

Revision ID: 36e997c57513
Revises:
Create Date: 2025-12-27 20:26:45.958595+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36e997c57513"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "cycle",
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("LEARNING", "STABLE", "UNSTABLE", name="cyclestate"),
            nullable=False,
        ),
        sa.Column("avg_cycle_length", sa.Integer(), nullable=True),
        sa.Column("avg_period_length", sa.Integer(), nullable=True),
        sa.Column("last_period_start", sa.DateTime(), nullable=True),
        sa.Column("last_evaluated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pid"),
    )
    with op.batch_alter_table("cycle", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cycle_pid"), ["pid"], unique=False)
        batch_op.create_index(batch_op.f("ix_cycle_user_id"), ["user_id"], unique=False)

    op.create_table(
        "period",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("luteal_length", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pid"),
    )
    with op.batch_alter_table("period", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_period_pid"), ["pid"], unique=False)
        batch_op.create_index(batch_op.f("ix_period_user_id"), ["user_id"], unique=False)

    op.create_table(
        "symptomevent",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "flow_intensity",
            sa.Enum("NONE", "SPOTTING", "LIGHT", "MEDIUM", "HEAVY", name="flowintensity"),
            nullable=True,
        ),
        sa.Column("symptoms", sa.JSON(), nullable=True),
        sa.Column("mood", sa.JSON(), nullable=True),
        sa.Column("ovulation_test", sa.Boolean(), nullable=True),
        sa.Column("discharge", sa.JSON(), nullable=True),
        sa.Column("sex", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("symptomevent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_symptomevent_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_symptomevent_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "temperature",
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pid"),
    )
    with op.batch_alter_table("temperature", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_temperature_pid"), ["pid"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_temperature_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_temperature_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "temperaturestate",
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "phase",
            sa.Enum("LEARNING", "LOW", "ELEVATED", "UNKNOWN", name="tempphase"),
            nullable=False,
        ),
        sa.Column("baseline", sa.Float(), nullable=True),
        sa.Column("last_evaluated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pid"),
    )
    with op.batch_alter_table("temperaturestate", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_temperaturestate_pid"), ["pid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_temperaturestate_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("temperaturestate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_temperaturestate_user_id"))
        batch_op.drop_index(batch_op.f("ix_temperaturestate_pid"))

    op.drop_table("temperaturestate")
    with op.batch_alter_table("temperature", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_temperature_user_id"))
        batch_op.drop_index(batch_op.f("ix_temperature_timestamp"))
        batch_op.drop_index(batch_op.f("ix_temperature_pid"))

    op.drop_table("temperature")
    with op.batch_alter_table("symptomevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_symptomevent_user_id"))
        batch_op.drop_index(batch_op.f("ix_symptomevent_id"))

    op.drop_table("symptomevent")
    with op.batch_alter_table("period", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_period_user_id"))
        batch_op.drop_index(batch_op.f("ix_period_pid"))

    op.drop_table("period")
    with op.batch_alter_table("cycle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cycle_user_id"))
        batch_op.drop_index(batch_op.f("ix_cycle_pid"))

    op.drop_table("cycle")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_user_id"))

    op.drop_table("user")
    # ### end Alembic commands ###
