"""empty message.

Revision ID: c49afbf749dd
Revises: a884a2645893
Create Date: 2026-01-10 21:15:15.742662+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c49afbf749dd"
down_revision: str | Sequence[str] | None = "a884a2645893"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partners",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("partner_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["partner_user_id"], ["user.user_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "partner_user_id"),
    )
    with op.batch_alter_table("partners", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_partners_partner_user_id"), ["partner_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_partners_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("partners", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_partners_user_id"))
        batch_op.drop_index(batch_op.f("ix_partners_partner_user_id"))

    op.drop_table("partners")
    # ### end Alembic commands ###
